### ISSUE TITLE
题库导入和模板

### ISSUE THREAD

**Issue by CodFrm** [CodFrm/cxmooc-tools#100]
## 题库导入模板
> **建议按照答案答题完成后提交答案,在答题页面让插件采集**

使用excel批量导入题库

模板:
![462BG`50448HV_SH(%{9$O](https://user-images.githubusercontent.com/22783163/70844939-a968fb00-1e83-11ea-9dac-b3e92e93c9a4.png)

文件:
[题库导入模板.xlsx](https://github.com/CodFrm/cxmooc-tools/files/3963559/default.xlsx)

建议提交时清除一次格式
![image](https://user-images.githubusercontent.com/22783163/70844965-f5b43b00-1e83-11ea-9154-01d294e88cea.png)

(后续会提供接口出来自由上传) #99 

题库导入后可以通过[*http://cx.icodef.com/query.html*](http://cx.icodef.com/query.html)进行查询

**Comment by Gyx200911** [comment]
我这漏题略多
如何补充题库？

**Comment by CodFrm** [comment]
> 我这漏题略多
> 如何补充题库？
@Gyx200911 
按照题库模板整理好,上传上来.或者做完题目之后让插件自动上传

**Comment by Gyx200911** [comment]
做完提莫 打开查看答案会自动上传是吧

**Comment by CodFrm** [comment]
@Gyx200911  是的,有一个框框提示

**Comment by Gyx200911** [comment]
> @ GYX0911 Yes, there is a frame hint.

判断题似乎无法上传答案

**Comment by CodFrm** [comment]
@Gyx200911 截图发出来看一下

**Comment by Gyx200911** [comment]
![QQ截图20200106224936](https://user-images.githubusercontent.com/10096675/71825518-051b5280-30d7-11ea-8c5f-e37ab048e966.jpg)

**Comment by CodFrm** [comment]
@Gyx200911 刚刚看了下数据库数据,题目采集是成功的,不过有点问题,方便的话可以提供一下账号吗?发我邮箱

答案可以在这里查找

http://cx.icodef.com/query.html

**Comment by Gyx200911** [comment]
> @Gyx200911 刚刚看了下数据库数据,题目采集是成功的,不过有点问题,方便的话可以提供一下账号吗?发我邮箱 [love@xloli.top](mailto:love@xloli.top)
> 
> 答案可以在这里查找
> 
> http://cx.icodef.com/query.html

emmm
我这边练习今早到期结束了
下次答题开了我再叫你

**Comment by CodFrm** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Trytoz"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 中午11:37
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;; 
抄送: "Farmer"<code.farmer@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CodFrm/cxmooc-tools] 题库导入模板 (#100)



 
@Gyx200911 刚刚看了下数据库数据,题目采集是成功的,不过有点问题,方便的话可以提供一下账号吗?发我邮箱 love@xloli.top
 
答案可以在这里查找
 
http://cx.icodef.com/query.html
  
emmm
 我这边练习今早到期结束了
 下次答题开了我再叫你

**Comment by emowt5** [comment]
请问一下怎么导入题库？

**Comment by CodFrm** [comment]
> 请问一下怎么导入题库？

@emowt5 按照上面给的模板整理题目,然后发上来

**Comment by emowt5** [comment]
[default.xlsx](https://github.com/CodFrm/cxmooc-tools/files/4218925/default.xlsx)

**Comment by emowt5** [comment]
怎么智慧树不像学习通一样能自动上传啊？

**Comment by CodFrm** [comment]
> 怎么智慧树不像学习通一样能自动上传啊？

智慧树有点麻烦,需要你点进去查看答案才行,很多人都不会点,所以智慧树题库也少

其实建议按照答案答题完成后提交答案,在答题页面让插件采集更好

你这里有做完之后的页面么?如果有的话,让插件自动上传比较好,我也就不手动导入了

**Comment by emowt5** [comment]
没有，有一章节我已经做完了，可是插件没显示自动上传

**Comment by emowt5** [comment]
智慧树的页面是不是需要用旧版的才行？

**Comment by CodFrm** [comment]
> 智慧树的页面是不是需要用旧版的才行？

@emowt5 是的,智慧树的新版还没有兼容

**Comment by Gyx200911** [comment]
我这闲着无聊弄了几个 验证码识别接口 来接入下？

**Comment by CodFrm** [comment]
@Gyx200911 有一个够了,没什么必要

**Comment by Gyx200911** [comment]
自闭在家俩月了 感觉要发霉

**Comment by Nchinasss** [comment]
[default.xlsx](https://github.com/CodFrm/cxmooc-tools/files/7779060/default.xlsx)

**Comment by Nchinasss** [comment]
我少量题测试一下格式对不对

**Comment by Nchinasss** [comment]
[default.xlsx](https://github.com/CodFrm/cxmooc-tools/files/7779075/default.xlsx)

**Comment by Nchinasss** [comment]
[default.xlsx](https://github.com/CodFrm/cxmooc-tools/files/7779188/default.xlsx)

**Comment by CodFrm** [comment]
> [default.xlsx](https://github.com/CodFrm/cxmooc-tools/files/7779188/default.xlsx)

ok

**Comment by Nchinasss** [comment]
我已经上传题库了为什么还是找不到？？？？是格式的问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodFrm/cxmooc-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 题库导入和模板 (#100)





  
default.xlsx
  
ok
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CodFrm** [comment]
可以在这里验证，题库是用的精准匹配，请确定题目无误
https://cx.icodef.com/query.html
![image](https://user-images.githubusercontent.com/22783163/147456811-99615d25-b53a-4c03-a6cb-66831d5690e8.png)

我看是有的

**Comment by Nchinasss** [comment]
我也找到了 但不知道为什么






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodFrm/cxmooc-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 题库导入和模板 (#100)





 
可以在这里验证，题库是用的精准匹配，请确定题目无误
 https://cx.icodef.com/query.html
 
 
我看是有的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nchinasss** [comment]
我发现在验证的时候用无格式的全题找不到反之删减几个字就能搜到了

**Comment by CodFrm** [comment]
> 

截图看一下题目

**Comment by Nchinasss** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodFrm/cxmooc-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 晚上8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 题库导入和模板 (#100)





   
截图看一下题目
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Nchinasss** [comment]
![5 $Y_B3WHNG0WD}Q{C@WMC8](https://user-images.githubusercontent.com/75122825/147483499-549499bc-5f4f-4ead-9850-d480f95478f3.png)


![3G%49)27Z@B NX4C6Z%1IWB](https://user-images.githubusercontent.com/75122825/147483492-a8af3f37-16c4-4096-b3ff-6192f43cc071.png)

**Comment by CodFrm** [comment]
@Nchinasss 应该是那个；干扰了  题库只能精准匹配

**Comment by Ender-William** [comment]
题库可以提供一种镜像方式吗，方便做镜像备份，或者能让有能力的人搭建本地服务器做本地搜索呢？
