### ISSUE TITLE
关于视频播放源

### ISSUE THREAD

**Issue by insight-21** [CodFrm/cxmooc-tools#103]
**错误描述**
视频播放源设置没有起到作用, 比如我播放源选择的是「公网1」, 但是长时间播放后就会自动切换成「本校」
以下为本人配置详情, 据测试, 油猴和Chrome插件两者都会出现这种错误:
let config = {
    answer_ignore: false,    //忽略题目,勾选此处将不会答题
    auto: true,              //全自动挂机,无需手动操作,即可自动观看视频等
    interval: 1.5,             //时间间隔,当任务点完成后,会等待5分钟然后跳转到下一个任务点
    rand_answer: true,      //随机答案,没有答案的题目将自动的生成一个答案
    video_multiple: 2,       //视频播放倍速,视频播放的倍数,建议不要改动,为1即可,这是危险的功能
    video_mute: true,        //视频静音,视频自动静音播放
    vtoken: "w4adagyruz",          //鉴权token,用于验证码打码,提交题目可获得打码次数
    video_cdn: "公网1"            //锁定视频播放源,为空为记录最后一次选中的源(公网1,公网2等)
};
https://graph.baidu.com/resource/126ff284e2fc36791568801581333083.jpg

https://graph.baidu.com/resource/126ba9a4622366a0b13c301581333327.jpg
(如果打不开请复制到浏览器)

**出现时间**
当长时间播放之后, 偶尔就会出现播放源自动切换到「本校」,然后因为没有连接校园网, 而停止播放,在两天使用过程中出现了至少4次

**错误版本**
浏览器版本: Chrome,

**Comment by CodFrm** [comment]
新版本已修复,等待测试和发布

**Comment by CodFrm** [comment]
新版本已经修复
