### ISSUE TITLE
npm run Server出错

### ISSUE THREAD

**Issue by dotagogo** [CodFrm/cxmooc-tools#105]
![Screenshot_2020-02-24-19-35-35-373_com sonelli juicessh](https://user-images.githubusercontent.com/26472193/75156553-52b65200-574d-11ea-899f-ccb993cd278b.png)
npm run server时出错，mongoDB版本是4.0.16，nodejs版本v11，帅哥，请问这如何解决呢？

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/75162587-bb56fc00-5758-11ea-8d7f-51db6e35ecf8.png)

将`serverConfig.mongoDB;`修改为`"mongodb://localhost:27017/cxmooc";`

或者增加config文件

**Comment by CodFrm** [comment]
如果没问题,我就关闭issue了
