### ISSUE TITLE
多选框里选了没显示

### ISSUE THREAD

**Issue by lhllhx** [CodFrm/cxmooc-tools#106]
**错误描述**
多选框里选了 但没显示 实际为选了尝试直接提交作业 成功满分
若复选 网站显示未做状态

![%RR _9FJNIQ{NC5 T`KZSVM](https://user-images.githubusercontent.com/52107206/75307647-374f6200-5887-11ea-81d4-3eff57fee7b6.png)

**出现时间**
能复现

**错误版本**
Chrome,火狐都有 都为商店最新版插件

**Comment by CodFrm** [comment]
切换使用智慧树的旧版答题试试,智慧树的新界面没有兼容

**Comment by lhllhx** [comment]
> 切换使用智慧树的旧版答题试试,智慧树的新界面没有兼容

旧版没有问题 感谢
建议加到文档中说明 
新版的智慧树里视频功能也不可用 旧版可用

**Comment by CodFrm** [comment]
旧版本不能访问了,再打开issue...

**Comment by CodFrm** [comment]
如果可以,希望能提供一下可以测试的账号,我这里没有账号能够去复现这个问题(就一个,没有单选题)

可以发到我的邮箱[love@xloli.top](love@xloli.top)

**Comment by StarunneR** [comment]
我曾经遇到过这个问题，但是这个问题并不是总是出现，所以复现有难度
记忆中只有需全部选中的多选题**有时**会出现这个问题
这是一个并不严重的bug，个人解决方法：隔天再试
可能是智慧树平台那边的问题

**Comment by CodFrm** [comment]
如果可以复现的话(新版本),希望可以提供账号 😶

**Comment by CodFrm** [comment]
已修复
