### ISSUE TITLE
智慧树旧版取消了

### ISSUE THREAD

**Issue by lhllhx** [CodFrm/cxmooc-tools#107]
智慧树旧版取消了  
![TIM截图20200227091911](https://user-images.githubusercontent.com/52107206/75403515-eef57a00-5942-11ea-9404-38a401055fed.png)

~~感觉有内鬼~~

**Comment by CodFrm** [comment]
有内鬼
![4D1X6 %SAHFA`HFSDNT}VND](https://user-images.githubusercontent.com/22783163/75403737-81961900-5943-11ea-95fb-e6d05a2d67c0.jpg)

我这边没有智慧树账号,还不能确认和兼容新版

**Comment by CodFrm** [comment]
兼容了,我现在更新到各个平台

**Comment by lhllhx** [comment]
> 兼容了,我现在更新到各个平台

感谢 最后提一个功能建议
在新版智慧树的作业板块里屏蔽了右键
建议增加一个去除这个js的功能

**Comment by CodFrm** [comment]
> > 兼容了,我现在更新到各个平台
> 
> 感谢 最后提一个功能建议
> 在新版智慧树的作业板块里屏蔽了右键
> 建议增加一个去除这个js的功能

感觉可以,我加到todo里去
