### ISSUE TITLE
您好，您的代码未经授权便被盗用

### ISSUE THREAD

**Issue by kermonds** [CodFrm/cxmooc-tools#108]
开发者您好，目前在国内Bilibili.com视频平台上发现数个教授使用您代码的视频，涉及到tampermonkey的脚本使用。
目前超星，智慧树等平台均在近日对记录予以严查。
此记录仅为通告，目的在于提醒开发者一些状况。
希望暂且delay新版本的开发与发布。

**Comment by CodFrm** [comment]
好的已经收到了,谢谢提醒
