### ISSUE TITLE
挂机模式2反馈地址

### ISSUE THREAD

**Issue by CodFrm** [CodFrm/cxmooc-tools#11]
如果挂机模式2使用之后没有问题,就有办法实现全自动挂机了

如果有朋友使用之后,可以在下方回复反馈,23333(被检测到会在首页提示诚信学习),我的账号之前测试已经被提示了

挂机模式2说明:

是在秒过视频上面的增强,秒过只发送最后一个封包,欺骗服务器播放完成,时间没有流逝

挂机模式2会在开始时发送一个封包,中间如果有题目会延迟几秒,然后提交题目的封包,最后提交结束的封包,时间会流逝,完成后会提示一个**信息框**

和[挂机模式]不同的是中间**不用播放视频**,不需要手动去做题目

------
补充

挂机模式2点击后按钮会变成停止挂机,不需要播放视频,完成后会弹出信息框提示....

主要还是测试会不会被系统检测到的问题

**Comment by kuangshao11** [comment]
我点了以后什么效果都没有....还是正常挂机的样子

**Comment by CodFrm** [comment]
@kuangshao11 是这样的,点击后按钮会变成停止挂机,不需要播放视频,完成后会弹出信息框提示...

**Comment by smithedwin201** [comment]
虽然一般要播放到中间手动把题目做了才能显示通过，不过还是挺好用的

**Comment by X237743972** [comment]
警告！在手机版详情内看得到视频情况，观看时间有时候是5分钟而不是完全观看，但是任务点已解锁。这种情况虽然没有不浪记录但是极有可能秋后算账！大家是不是这种情况，一定要小心挂机模式2

**Comment by CodFrm** [comment]
@X237743972 了解了,可怕

**Comment by CodFrm** [comment]
@X237743972 问一下,你的观看时间这个是在那里看到的,我没有找到唉

**Comment by CodFrm** [comment]
挂机模式2弃用,已经有更好的操作方法了
