### ISSUE TITLE
给各位其他用户和开发者提醒

### ISSUE THREAD

**Issue by zjh4473** [CodFrm/cxmooc-tools#111]
此产品是非常好的产品，非常推荐大家使用，但是请各位用户和开发者加群前注意。
此群管理QQ：246456560 EmpTomation

权限狗警告。权限狗警告。权限狗警告。

**Comment by JunzhouLiu** [comment]
> 此产品是非常好的产品，非常推荐大家使用，但是请各位用户和开发者加群前注意。
> 此群管理QQ：246456560 EmpTomation
> 
> 权限狗警告。权限狗警告。权限狗警告。

权限狗虽然恶心，但是这个项目是开源项目，总是遇到付费软件很少存在的奇葩用户，还有各种白嫖还不够，还要拿开源软件去赚钱的用户，所以权限狗能让开发者少接触这些用户，安心开发，不受气，所以我还蛮喜欢群里的权限狗，虽然权限狗恶心，但是权限狗在这里 就是天使，恶心的天使。

**Comment by zjh4473** [comment]
> > 此产品是非常好的产品，非常推荐大家使用，但是请各位用户和开发者加群前注意。
> > 此群管理QQ：246456560 EmpTomation
> > 权限狗警告。权限狗警告。权限狗警告。
> 
> 权限狗虽然恶心，但是这个项目是开源项目，总是遇到付费软件很少存在的奇葩用户，还有各种白嫖还不够，还要拿开源软件去赚钱的用户，所以权限狗能让开发者少接触这些用户，安心开发，不受气，所以我还蛮喜欢群里的权限狗，虽然权限狗恶心，但是权限狗在这里 就是天使，恶心的天使。

是的，但是随意权限就是死妈傻逼了。
