### ISSUE TITLE
[非bug] 技术讨论

### ISSUE THREAD

**Issue by weihai4099** [CodFrm/cxmooc-tools#114]
咨询一下，我最近开始刷课，遇到了鼠标移出自动暂停的问题。我发现是video标签有mouseout事件。然后我也想写个插件自动把mouseout事件给去除。然后问题是无法通过removeeventlistener方法去移除事件处理。必须要提供方法名。然后搜索到这个插件。发现是下面的第二行。

```js
self.video = $(self.document).find('#video_html5_api')[0];
self.iframe.contentWindow.Ext.fly(self.document).un('mouseout');
let html = $(self.iframe).parents('body')[0].innerHTML;
self.mArg = JSON.parse('{' + common.substrEx(html, 'mArg = {', ';'));
for (let i = 0; i < self.mArg.attachments.length; i++) {
      if (self.mArg.attachments[i].objectId == $(self.iframe).attr('objectid')) {
          self.videoMsg = self.mArg.attachments[i];
          break;
     }
}
```

然后我大概查了一下ext是一个js框架。之前也没用过，也没听说过。有两个问题咨询一下：

1. 我全局搜索ext三个字母，没发现是怎么引入的工程，或者压根不是ext库？但是fly函数又有点怀疑
2. Ext.fly(self.document).un('mouseout'); 这里为什么可以移除掉mouseout事件处理的？匿名函数的问题这里请解答一下。

**Comment by CodFrm** [comment]
这个方法是一个大佬告诉我的

可以从这个网址去下手:https://mooc1-1.chaoxing.com/ananas/modules/video/index.html?v=2019-1113-1705 超星视频iframe调用的就是这个网址

近期优化插件我也去简略的看了超星的刷课源码

Ext 是超星自己的框架, 注册地址:https://mooc1-1.chaoxing.com/ananas/ext-4.2.0.663/all-classes.js?v=2020-0308-1102

fly 函数行数:https://mooc1-1.chaoxing.com/ananas/ext-4.2.0.663/all-classes.js?v=2020-0308-1102:formatted:9977

![image](https://user-images.githubusercontent.com/22783163/76719855-02437a80-6776-11ea-9287-01536cecf6bd.png)

可以自己调试去看结果 建议用fiddler之类工具格式化js代码,替换原来的地址,不然调试容易卡住

**Comment by weihai4099** [comment]
已经找到了，谢谢
