### ISSUE TITLE
最近似乎出现 测试答题 提交一次后 剩下的全部会 提交错误

### ISSUE THREAD

**Issue by Gyx200911** [CodFrm/cxmooc-tools#115]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
Chrome

**Comment by CodFrm** [comment]
不太懂楼主的描述

**Comment by CodFrm** [comment]
楼主太长时间没有恢复,关闭issue
