### ISSUE TITLE
智慧树无法倍速，答案搜索显示无答案

### ISSUE THREAD

**Issue by niliqiang** [CodFrm/cxmooc-tools#116]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图
智慧树无法倍速，答案搜索显示无答案
![image](https://user-images.githubusercontent.com/41098158/76724857-5f93f780-6787-11ea-971c-43d63ce80a84.png)

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)
```js
{enforce: false, hotversion: "2.117", url: "https://github.com/CodFrm/cxmooc-tools/releases", version: "2.11"}
enforce: false
hotversion: "2.117"
url: "https://github.com/CodFrm/cxmooc-tools/releases"
version: "2.11"
__proto__:
constructor: ƒ Object()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
hasOwnProperty: ƒ hasOwnProperty()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toString: ƒ toString()
valueOf: ƒ valueOf()
toLocaleString: ƒ toLocaleString()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```
**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)
一直出现

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?
Chrome浏览器版本：80.0.3987.132（正式版本） （64 位）
扩展版本：2.1.17

**Comment by CodFrm** [comment]
智慧树倍速是按照右边的那个百分比进行的,倍速对智慧树无效

搜索不到题目确实是题库的确实,没有这个答案,下个版本会优化题目收集的功能

**Comment by niliqiang** [comment]
> 智慧树倍速是按照右边的那个百分比进行的,倍速对智慧树无效
> 
> 搜索不到题目确实是题库的确实,没有这个答案,下个版本会优化题目收集的功能

好的，感谢，为大佬的回复速度点赞
