### ISSUE TITLE
[智慧树反馈]智慧树似乎无法工作

### ISSUE THREAD

**Issue by luojunyuan** [CodFrm/cxmooc-tools#117]
**错误描述**
1. console 中输入cxmooc筛选后，没有内容
![filter1](https://i.loli.net/2020/03/17/rc9ijyLhCaePmk6.png)
筛选后
![filter2](https://i.loli.net/2020/03/17/xG8R9Bfk1DtINEa.png)

2. 自动跳过视频似乎没有工作，我设置时间为0.5分钟，选择了一个之前看过的视频跳到最后。等待半晌也没有反应，控制台只有视频播放和暂停时会输出反馈（如图1）
![auto](https://i.loli.net/2020/03/17/mcPTBafHobnJ5wY.png)

3. 视频途中弹出的几道题目不会响应
![problem](https://i.loli.net/2020/03/17/pKMs28rhdUtzoEq.png)

**错误提示和日志内容**
 如错误描述中的1所述

**出现时间**
尝试多次无效

**错误版本**
使用的centBrowser打包版
cxmooc-tools v2.117
视频域名备注
`https://studyh5.zhihuishu.com/videoStudy.html#/studyVideo`

**Comment by CodFrm** [comment]
尝试下载一下新的打包版本试一下?

打包版本有更新但是没有推送更新通知

浏览器打包版(下载之后直接打开exe文件,然后访问超星慕课网站就可以使用)
链接：https://pan.baidu.com/s/1Kji5J-e-AYrDry0NwRZy4Q
提取码：asgm

**Comment by luojunyuan** [comment]
成功了，没有想到我之前的打包版本是2.11不是最新的。谢谢，一切正常了
