### ISSUE TITLE
题库里的答案开始有错了，插件本身工作得很好。

### ISSUE THREAD

**Issue by cwnevergg** [CodFrm/cxmooc-tools#118]
**错误描述**
题库里的答案开始有错了，都能某个任务点的题都可以搜到
但不能像以前那样全bingo了，大概每10个会错误2个

**错误提示和日志内容**
拓展本身无错误

**出现时间**
第一次出现大概在2020-3-9

**错误版本**
firefox 74.0 64bit on Mac OS X 10.15.3
cxmooc-tools v2.117

**Comment by CodFrm** [comment]
把错误的答案截图看一下？有没有勾选随机答案？

后续会更新一个错题反馈的功能，对题目的上传也会加以限制

**Comment by cwnevergg** [comment]
> 把错误的答案截图看一下？有没有勾选随机答案？
> 
> 后续会更新一个错题反馈的功能，对题目的上传也会加以限制

没有勾选随机答案，这些有错误答案的题的共同特点是它的题目本身的源是图片，而不是文字，文字叙述也在图片上(数学)

**Comment by CodFrm** [comment]
能截图几个类似题目吗?

**Comment by cwnevergg** [comment]
> 能截图几个类似题目吗?

[https://github.com/cwnevergg/a-simple-MIS/blob/master/%E6%88%AA%E5%B1%8F2020-03-19%E4%B8%8B%E5%8D%887.54.25.png](url)
[https://github.com/cwnevergg/a-simple-MIS/blob/master/%E6%88%AA%E5%B1%8F2020-03-19%E4%B8%8B%E5%8D%887.54.47.png](url)

**Comment by cwnevergg** [comment]
![avatar](https://github.com/cwnevergg/a-simple-MIS/blob/master/%E6%88%AA%E5%B1%8F2020-03-19%E4%B8%8B%E5%8D%887.54.47.png)

**Comment by cwnevergg** [comment]
<img width="692" alt="截屏2020-03-19下午7 54 25" src="https://user-images.githubusercontent.com/41811773/77066034-5f148e80-6a1d-11ea-8019-29f3064e9f28.png">
<img width="692" alt="截屏2020-03-19下午7 54 47" src="https://user-images.githubusercontent.com/41811773/77066040-6340ac00-6a1d-11ea-8269-efed5e789414.png">

**Comment by CodFrm** [comment]
麻烦给一个图片链接,我去数据库里面看看数据的记录情况

第二题的吧

**Comment by cwnevergg** [comment]
> 麻烦给一个图片链接,我去数据库里面看看数据的记录情况
> 
> 第二题的吧

sorry，不懂web相关，不知道正确的issue姿势。
[http://p.ananas.chaoxing.com/star3/origin/be212009032c2ae63561192f24683e27.png](url)
[http://p.ananas.chaoxing.com/star3/origin/d47e2fe80f53df93681bd69e420a7389.png](url)

**Comment by CodFrm** [comment]
确定了,应该是这边采集的问题,我把那个记录去掉了

**Comment by CodFrm** [comment]
后续增加错题反馈之类的功能来解决吧

**Comment by cwnevergg** [comment]
> 后续增加错题反馈之类的功能来解决吧

请一定注意检查，万一有人捣乱把正确的答案反馈成错题。。

**Comment by CodFrm** [comment]
@cwnevergg 之前人数少,几乎没有权限,现在鱼龙混杂,是应该要操作一下了...

**Comment by cwnevergg** [comment]
> @cwnevergg 之前人数少,几乎没有权限,现在鱼龙混杂,是应该要操作一下了...

多谢！

**Comment by cwnevergg** [comment]
@CodFrm  [http://p.ananas.chaoxing.com/star3/origin/c21f26c852cda9627a75edc83e83f8f2.png](url)
[http://p.ananas.chaoxing.com/star3/origin/f2ae96c2a93db98a45133e14a9bc5427.png](url)
另一门课也中枪了[doge]  迫在眉睫呀

**Comment by cwnevergg** [comment]
有相似问题issue且正在解决，关闭这个issue

**Comment by cwnevergg** [comment]
<img width="1020" alt="截屏2020-03-31 下午8 20 54" src="https://user-images.githubusercontent.com/41811773/78025923-66c52300-738d-11ea-8292-39421e2a1c33.png">
再次出现了题库答案错误，不过数量比起上次来说极少，属于多选题没选全的情况。

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/78026313-fe2a7600-738d-11ea-99fa-f210913e77ab.png)
这种的题库可以自动更新
