### ISSUE TITLE
Chrome加载扩展程序时出错

### ISSUE THREAD

**Issue by Qk1hpys** [CodFrm/cxmooc-tools#12]
是我自己的问题？
**无论是使用`crx`文件添加，还是直接用源码添加文件夹，都不行。**
大家能用吗?

**Comment by CodFrm** [comment]
@Qk1hpys https://github.com/CodFrm/cxmooc-tools#%E6%96%B9%E6%B3%951

chrome浏览器的话crx文件解压然后加载才可以使用
