### ISSUE TITLE
请问mac版本应该怎么安装呢

### ISSUE THREAD

**Issue by zzzy1104** [CodFrm/cxmooc-tools#120]

**Comment by CodFrm** [comment]
安装好chrome浏览器,按照
http://cx.icodef.com/1-UserGuide/1-1-chrome.html
这里进行扩展安装

**Comment by zzzy1104** [comment]
解压的时候报错：无法提取文件。该压缩文件可能已损坏或密码无效。请问这个该怎么解决呀

**Comment by CodFrm** [comment]
那你用这个解压试试:https://github.com/CodFrm/cxmooc-tools/releases/download/v2.1.1/cxmooc-tools.zip

**Comment by zzzy1104** [comment]
解决了！谢谢！！
