### ISSUE TITLE
填空题问题

### ISSUE THREAD

**Issue by LiRunyang** [CodFrm/cxmooc-tools#121]
遇到填空题的时候默认会在第一个空把所有答案都填上去，剩下的都填不上，而且它默认是填答案的，也就是说在答案错的时候你要手动把正确答案输进去

填空题会出现问题

Chrome 80.0

**Comment by CodFrm** [comment]
能发一个类似的题目上来吗?截图就好

**Comment by LiRunyang** [comment]
![image](https://user-images.githubusercontent.com/56293554/77028526-f523c700-69d3-11ea-8d15-cb1c9fe862c3.png)

**Comment by LiRunyang** [comment]
而且这里题库也有点问题，估计是其他人人工写的？

**Comment by CodFrm** [comment]
题目能也截图下来吗?

可能是题目有修改过,之前是一空全填的采集上传后,所以第一空全填了

**Comment by LiRunyang** [comment]
![image](https://user-images.githubusercontent.com/56293554/77028988-6748db80-69d5-11ea-82ab-596f87346e91.png)
![image](https://user-images.githubusercontent.com/56293554/77029009-7af44200-69d5-11ea-9172-7c6fff365a96.png)

**Comment by CodFrm** [comment]
=_=....好的...大概知道了 应该是插件采集的问题

**Comment by CodFrm** [comment]
不过好在应该能批量处理这个问题

**Comment by CodFrm** [comment]
插件版本已更新

**Comment by CodFrm** [comment]
处理完毕
