### ISSUE TITLE
大学物理题库出现很多错题

### ISSUE THREAD

**Issue by G2killer** [CodFrm/cxmooc-tools#123]

**Comment by CodFrm** [comment]
题目截图发上来看一下

**Comment by G2killer** [comment]
![image](https://user-images.githubusercontent.com/61378198/77241164-7922bc80-6c29-11ea-9be0-02693af8572c.png)
![image](https://user-images.githubusercontent.com/61378198/77241165-7f189d80-6c29-11ea-8b5d-a6f67175683e.png)
![image](https://user-images.githubusercontent.com/61378198/77241169-8b045f80-6c29-11ea-8ce6-a12eb4d54238.png)

**Comment by CodFrm** [comment]
了解了,新版本会做优化

**Comment by cwnevergg** [comment]
前几天是十个错两个。。现在十个错八个。。

**Comment by cwnevergg** [comment]
> 前几天是十个错两个。。现在十个错八个。。

很好奇，之前为什么一个都没有，是不是进老鼠了

**Comment by CodFrm** [comment]
> > 前几天是十个错两个。。现在十个错八个。。
> 
> 很好奇，之前为什么一个都没有，是不是进老鼠了
@cwnevergg 
题目的处理出了问题,你可以试试在这个网站查询
http://cx.icodef.com/query.html

**Comment by CodFrm** [comment]
插件版本已经进行了热更新 v2.118

但是还有一些类型的题目无法解决,难受

**Comment by G2killer** [comment]
现在好多了，正确率上升了不少，基本全对了。建议增加一个可以刷访问数的功能。
