### ISSUE TITLE
关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。

### ISSUE THREAD

**Issue by KatharsisKing** [CodFrm/cxmooc-tools#125]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
不用最小化窗口

**Comment by KatharsisKing** [comment]
不是最小化窗口，多开了
不能最小化吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:01
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。 (#125)





 
不用最小化窗口

**Comment by CodFrm** [comment]
最小化情况下受到了浏览器的限制无法播放视频

如果没有最小化,新版本已经对这一块进行了优化,有时间的话这周会在应用商店发布

**Comment by KatharsisKing** [comment]
案例，火狐
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:04
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。 (#125)





 
最小化情况下受到了浏览器的限制无法播放视频
 
如果没有最小化,新版本已经对这一块进行了优化,有时间的话这周会在应用商店发布

**Comment by KatharsisKing** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:04
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。 (#125)





 
最小化情况下受到了浏览器的限制无法播放视频
 
如果没有最小化,新版本已经对这一块进行了优化,有时间的话这周会在应用商店发布

**Comment by CodFrm** [comment]
你的邮件回复越来越乱了.....

**Comment by KatharsisKing** [comment]
大佬，我意思您可能没明白，在视频最后一帧或者第一帧就暂停了，需要手动点一下。麻烦了大佬，谢谢您


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:04
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。 (#125)





 
最小化情况下受到了浏览器的限制无法播放视频
 
如果没有最小化,新版本已经对这一块进行了优化,有时间的话这周会在应用商店发布

**Comment by CodFrm** [comment]
明白,新版本应该会解决

**Comment by KatharsisKing** [comment]
如图，就这样，黑屏，需要手动点，刚刚收到邮件，麻烦您了，大概就是这样。
------------------ 原始邮件 ------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 下午4:12
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 关于视频莫名暂停，黑屏的现象，常常在视频最后，或者视频一开始加载出现，经常挂了很久还是不动，浪费了很多时间，望大佬修改一下代码。谢谢。 (#125)





 
你的邮件回复越来越乱了.....

**Comment by CodFrm** [comment]
新版本已经发布在商城,麻烦确认一下有没有解决
