### ISSUE TITLE
超星平台一个页面多视频时，只会自动播放第一个，望更新！

### ISSUE THREAD

**Issue by StudentWH** [CodFrm/cxmooc-tools#126]
**错误描述**
如图，在超星平台上，当一个学习页面中包括多个视频时，插件能够检测到所有视频，但是只能自动播放第一个，其它的视频需要手动点击开始挂机。
![image](https://user-images.githubusercontent.com/44202506/77600842-fd37b580-6f43-11ea-9b92-acd53837dc40.png)
![image](https://user-images.githubusercontent.com/44202506/77600877-1fc9ce80-6f44-11ea-85f6-04652be0124c.png)

**错误版本**
Chrome 64.0
插件：超星慕课的小工具，版本：2.1.17

**Comment by CodFrm** [comment]
已经准备更新

**Comment by CodFrm** [comment]
新版本已经发布在商城,麻烦确认一下有没有解决

**Comment by StudentWH** [comment]
收到，非常感谢。
&nbsp; &nbsp; 1、一个页面多视频播放的问题已经解决。
&nbsp; &nbsp; 2、但是看见另一位提出issue：挂机需要手动进行操作，一个视频挂完，刷新页面到下一节，视频不会自动播放，小概率抽风。
&nbsp; &nbsp; &nbsp; &nbsp; 看他之前也提过这个问题，它的是fireFox，我的是Chrome，也出现这个问题：
&nbsp; &nbsp; &nbsp; &nbsp; 当跳转到下一个页面后，新视频会进入挂机过程，但是视频本身处于黑屏，需要手动点击一下页面，视频才会真正的播放。目前不确定是由于我自身网络问题，还是其它原因。
&nbsp; &nbsp; 再次感谢大佬！






------------------
Best wishes,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Yours,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Tian yongsheng　　　　　　　　　　　　　　　　　　　　　
South-Central University For Nationalities
Wuhan, Hubei 430074, P.R.CHINA




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 上午9:12
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"田永胜"<tiansheng.33@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 超星平台一个页面多视频时，只会自动播放第一个，望更新！ (#126)





 
新版本已经发布在商城,麻烦确认一下有没有解决
