### ISSUE TITLE
挂机需要手动进行操作，一个视频挂完，刷新页面到下一节，视频不会自动播放，小概率抽风。

### ISSUE THREAD

**Issue by KatharsisKing** [CodFrm/cxmooc-tools#127]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
新版本已经优化

**Comment by KatharsisKing** [comment]
就是新版本。



---原始邮件---
发件人: "CodFrm"<notifications@github.com&gt;
发送时间: 2020年3月26日(周四) 中午11:42
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"KatharsisKing"<1014799680@qq.com&gt;;
主题: Re: [CodFrm/cxmooc-tools] 挂机需要手动进行操作，一个视频挂完，刷新页面到下一节，视频不会自动播放，小概率抽风。 (#127)




 
新版本已经优化

**Comment by KatharsisKing** [comment]
新版的吧，挂机点了不是暂停挂机了对吧，为什么不播放呢？Firefox浏览器，谢谢大佬了。昨天刚来过，今天又来了。


------------------ 原始邮件 ------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午11:42
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 挂机需要手动进行操作，一个视频挂完，刷新页面到下一节，视频不会自动播放，小概率抽风。 (#127)





 
新版本已经优化

**Comment by KatharsisKing** [comment]
新版的吧，挂机点了不是暂停挂机了对吧，为什么不播放呢？Firefox浏览器，谢谢大佬了。昨天刚来过，今天又来了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午11:42
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Katharsis King"<1014799680@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 挂机需要手动进行操作，一个视频挂完，刷新页面到下一节，视频不会自动播放，小概率抽风。 (#127)





 
新版本已经优化

**Comment by CodFrm** [comment]
新版本已经发布在商城,麻烦确认一下有没有解决
