### ISSUE TITLE
一些多选题答案不止4个，但是题库中好像默认最多保存4个答案，之后新增的答案不会保存

### ISSUE THREAD

**Issue by keyis12138** [CodFrm/cxmooc-tools#128]

**Comment by CodFrm** [comment]
新增的会进行合并保存

**Comment by keyis12138** [comment]
![} O@NLC7W0RQ)1D54_RD4T6](https://user-images.githubusercontent.com/45349278/77752655-f0f64a00-7062-11ea-9b98-3da839374157.png)
像这题，我已经fan反复提交很多次了，但是他仍然会漏选一项

**Comment by CodFrm** [comment]
正确答案是abcd么?有点奇怪,中国mooc应该是会一次性上传完成的,所以没有做合并处理.能把这个课程和测试的位置发我么?(不知道链接可不可以

**Comment by keyis12138** [comment]
武汉大学的毛概第13章的测试[https://www.icourse163.org/learn/WHU-1001716008?tid=1450261456#/learn/announce](url)

**Comment by CodFrm** [comment]
我明白了,我以为会一次性显示出来了.... 😭 
周末修复

**Comment by keyis12138** [comment]
好哒，多谢大佬

**Comment by CodFrm** [comment]
修复了,可以看看

**Comment by keyis12138** [comment]
多谢大佬，测试过了，确实能记录多出来的答案了

**Comment by keyis12138** [comment]
等等，是只修了那一个测验吗，第九章的测验还是会出现这样的问题
![@WTVJ4N I25I)BF4%H%SMNJ](https://user-images.githubusercontent.com/45349278/77825648-9bdf3480-7145-11ea-86b2-c224d832f08f.png)

**Comment by keyis12138** [comment]
图好像一直裂，，，题目是：党的十九大指出，到本世纪中叶我国建成社会主义现代化强国的目标有（  ）。
”我国将拥有高度的物质文明“这个选项不会被选中。

**Comment by CodFrm** [comment]
我查询到是采集到了,可能你那个时候还没采集上来?

![image](https://user-images.githubusercontent.com/22783163/77826837-e912d480-714c-11ea-990c-3705e400a65f.png)

**Comment by CodFrm** [comment]
我没找到这道题=_=  发下链接?

我看了一下数据库...超星也有一个同样的题目,它少了一个选项,我不确定是不是因为这个导致的

**Comment by keyis12138** [comment]
emmm，刚试了一下，现在有选那个选项了，，，延迟这么高？

**Comment by CodFrm** [comment]
😹😹不太清楚，应该是没有延迟的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: keyis12138 <notifications@github.com&gt;
发送时间: 2020年3月29日 00:16
收件人: CodFrm/cxmooc-tools <cxmooc-tools@noreply.github.com&gt;
抄送: CodFrm <code.farmer@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[CodFrm/cxmooc-tools] 一些多选题答案不止4个，但是题库中好像默认最多保存4个答案，之后新增的答案不会保存 (#128)





 
emmm，刚试了一下，现在有选那个选项了，，，延迟这么高？
