### ISSUE TITLE
怎么可以一键挂机啊？

### ISSUE THREAD

**Issue by smartAndgoodMark** [CodFrm/cxmooc-tools#13]
就是启动后，自动把同一课程没看完的页面都看完
是我没弄明白还是还没开发这项功能呢

**Comment by CodFrm** [comment]
@smartAndgoodMark 还没有开发这一项功能呢

**Comment by smartAndgoodMark** [comment]
@CodFrm 好吧，还以为是readme没介绍清楚呢

**Comment by CodFrm** [comment]
@smartAndgoodMark hah,还在慢慢完善
