### ISSUE TITLE
添加课件下载功能

### ISSUE THREAD

**Issue by Repobor** [CodFrm/cxmooc-tools#130]
https://greasyfork.org/zh-CN/scripts/397190-%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E8%AF%BE%E7%A8%8B%E8%B5%84%E6%BA%90%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD
可以整合下这个脚本

**Comment by CodFrm** [comment]
借鉴了他的思路优化了现在的video视频下载,后续会加上ppt等的下载,不知道这样好不好 😢

**Comment by CodFrm** [comment]
已经增加,可以尝鲜

https://github.com/CodFrm/cxmooc-tools/pull/138#issuecomment-606723023
