### ISSUE TITLE
视频播放过程中会自动暂停之后自动恢复播放

### ISSUE THREAD

**Issue by 1010joymo** [CodFrm/cxmooc-tools#132]
新更新了版本之后，视频播放过程中会自动暂停（大概1秒），之后自动恢复正常播放。
chrome插件2.2版本。求解答谢谢

**Comment by CodFrm** [comment]
蛤?这么奇怪的问题? 是不是因为网络,视频没有加载出来

**Comment by 1010joymo** [comment]
并不是，B站1080p播放无卡顿，刚刚重启浏览器，发现自动暂停的时间更久了，两三秒左右然后自动恢复正常播放，只有我遇到这个问题吗？

**Comment by CodFrm** [comment]
b站播放没问题,不证明超星没问题

你可以截图上来看看

**Comment by 1010joymo** [comment]
[超星bug.zip](https://github.com/CodFrm/cxmooc-tools/files/4396876/bug.zip)

**Comment by CodFrm** [comment]
确定了,网络问题, 你可以看这里 它的缓冲进度是很少的 和插件无关

![image](https://user-images.githubusercontent.com/22783163/77819760-51938e80-7118-11ea-885b-c47d8484fccf.png)

![image](https://user-images.githubusercontent.com/22783163/77819766-696b1280-7118-11ea-9c9c-8284dbeafcf5.png)

**Comment by 1010joymo** [comment]
ok，麻烦了。谢谢。

**Comment by CodFrm** [comment]
刚刚看了一下,是插件导致的bug  多视频的情况下会出现,准备修复 ,不好意思

**Comment by 1010joymo** [comment]
好的，感谢。

**Comment by CodFrm** [comment]
已更新,插件可能会有缓存,需要清理缓存,然后重新打开浏览器
