### ISSUE TITLE
mooc课后讨论还是不能刷

### ISSUE THREAD

**Issue by cj1916** [CodFrm/cxmooc-tools#134]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
课后讨论不在该版本支持范围内

https://github.com/CodFrm/cxmooc-tools/pull/124

**Comment by CodFrm** [comment]
与#129重复,关闭本issue
