### ISSUE TITLE
超新慕课音频无法自动播放。

### ISSUE THREAD

**Issue by FledgeXu** [CodFrm/cxmooc-tools#135]
### 功能描述
![image](https://user-images.githubusercontent.com/16664654/77867916-dba03c00-726b-11ea-832f-7186c129e5dc.png)
能否考虑添加自动播放音频的功能？

### 支援信息
chapterId=274465199
courseId=209809817
clazzid=20293456
课程名称：毛泽东思想和中国特色社会主义理论体系概论

**Comment by CodFrm** [comment]
这个在新版本的计划中

**Comment by CodFrm** [comment]
已经增加,可以尝鲜

https://github.com/CodFrm/cxmooc-tools/pull/138#issuecomment-606723023
