### ISSUE TITLE
关于增加自动签到的功能

### ISSUE THREAD

**Issue by xyyzy** [CodFrm/cxmooc-tools#136]
### 功能描述
> 增加自动签到功能，学生对这个需求其实很多，因为水课的签到查的反而很严
希望能够增加自动签到的功能
### 支援信息
> 提供账号或者课程的id等信息

**Comment by CodFrm** [comment]
自动签到你可以用这个软件,暂时好像没发,可以加群:713980830

**Comment by CodFrm** [comment]
插件暂时没有准备增加这个功能
