### ISSUE TITLE
希望能够支持ppt类型的任务点

### ISSUE THREAD

**Issue by tjy-ctrl** [CodFrm/cxmooc-tools#137]
目前不能刷ppt类型的任务点
希望支持一下

![SharedScreenshot](https://user-images.githubusercontent.com/62851401/77943732-4bf0a100-72f0-11ea-8bf9-ea9b3d550006.jpg)

**Comment by CodFrm** [comment]
在下一个版本计划中

**Comment by CodFrm** [comment]
与#109 重复,关闭issue
