### ISSUE TITLE
Linux Chrome 无法正常运作

### ISSUE THREAD

**Issue by March-happy** [CodFrm/cxmooc-tools#14]
1.直接把 .crx 拖到 Chrome 里，插件出现了一下然后立刻消失。

正在测试 npm 自己 build 的版本🤣

**Comment by CodFrm** [comment]
@March-happy 这个....linux没试过,按理来说是支持的,不过我的应用没发布在google商店,可能因为这个原因所以扩展不允许安装,试试开发者模式?
