### ISSUE TITLE
超星平台更新到2.2之后无法再进行同一个页面的多个视频同时放了，希望重新支持同时播放

### ISSUE THREAD

**Issue by cwnevergg** [CodFrm/cxmooc-tools#143]
### 功能描述
> 需要实现的功能的表示
2.2之前使用的时候经常会停掉自动挂机这个功能，然后同时开始播放一个页面中的好几个视频，
此时无论鼠标移开还是其他动作都不会停掉同时播放的好几个视频，更新到2.2之后只能一个一个的看了，乱移动鼠标(不点击)会导致一些视频停下来。还有一些视频的按钮被挡住了。
<img width="749" alt="截屏2020-04-02 下午12 36 45" src="https://user-images.githubusercontent.com/41811773/78211083-a2233700-74de-11ea-962a-9a597ab18450.png">

**Comment by CodFrm** [comment]
修复了

**Comment by CodFrm** [comment]
按钮被拦住- -...我记得是解决了呀....我更新一下,看看还会不会出现

**Comment by CodFrm** [comment]
已经更新
