### ISSUE TITLE
那种通过活动发出的随堂测验无法进行搜题

### ISSUE THREAD

**Issue by G2killer** [CodFrm/cxmooc-tools#144]
![image](https://user-images.githubusercontent.com/61378198/78421476-9aa09100-768a-11ea-8963-5123dbd9a3a7.png)
类似于这种，没有办法搜题。

**Comment by CodFrm** [comment]
在以后的支持计划中,与 https://github.com/CodFrm/cxmooc-tools/issues/142 重复,关闭本issue
