### ISSUE TITLE
换到其他标签页就无法自动播放下一个视频

### ISSUE THREAD

**Issue by Xin929** [CodFrm/cxmooc-tools#145]
请问超星刷课除了不能点最小化外是不是也不能在同一个浏览器的其他标签页浏览网页，我试了火狐浏览器和edge谷歌内核版都只能自动跳到下一个视频的页面但不能自动播放下一个视频，但是智慧树就没有这种问题。超星刷课的话是不是必须用一个浏览器专门放着刷，然后用另一个浏览器浏览网页？

**Comment by CodFrm** [comment]
是的,不能切换标签也不能最小化

但是你可以切换窗口

**Comment by CodFrm** [comment]
智慧树可以是因为他是一个单页面,超星是iframe(猜测,没去验证)

**Comment by Xin929** [comment]
> 是的,不能切换标签也不能最小化,这是浏览器的限制
> 
> 但是你可以切换窗口
> 
> 听闻360浏览器可以,你可以尝试一下

哦哦好的谢谢
