### ISSUE TITLE
题库相关问题

### ISSUE THREAD

**Issue by lhllhx** [CodFrm/cxmooc-tools#149]
智慧树平台
这类型的题目无法识别 建议这类型题目加入对答案的匹配
![TIM图片20200407234027](https://user-images.githubusercontent.com/52107206/78690005-84643080-7929-11ea-933e-7f60c8f84dcd.png)

**Comment by CodFrm** [comment]
题目太通配了=_=

等处理完超星的题库,会去处理智慧树的

**Comment by lhllhx** [comment]
给个建议 把这些通配题一个统一的答案题库 用每一个选项去索引答案题库

**Comment by CodFrm** [comment]
已经拿试卷id作为一个索引了

**Comment by NewbeBrynbo** [comment]
如果有些老师自行上传的题目不包含在题库里面的话，只能自己写了吧

**Comment by CodFrm** [comment]
> 如果有些老师自行上传的题目不包含在题库里面的话，只能自己写了吧

这个是的,可以找同学采集录入一下
