### ISSUE TITLE
超星-考试版块题目上传问题

### ISSUE THREAD

**Issue by MartyAlien** [CodFrm/cxmooc-tools#150]
### 功能描述
> 需要实现的功能的表示
超星小工具是自动上传题目的，上传成功后能提示相关信息，但是我进入考试中的题目页面时，没有任何提示消息，不知道是否能成功上传题目
### 支援信息
> 提供账号或者课程的id等信息

**Comment by CodFrm** [comment]
不知道你进的是什么页面,考试有时候不会显示正确答案或者正确与否,所以可能不会提交上来

考试这两天会进行优化

**Comment by MartyAlien** [comment]
我进入的是已经考过且有成绩有答案的界面，测试了我的所有课程都没有提示（请见图）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 上午9:23
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Imp@tan"<monster8alien@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 超星-考试版块题目上传问题 (#150)





 
不知道你进的是什么页面,考试有时候不会显示正确答案或者正确与否,所以可能不会提交上来
 
考试这两天会进行优化

**Comment by CodFrm** [comment]
图片?没有看见 😂

**Comment by MartyAlien** [comment]
![12](https://user-images.githubusercontent.com/62040646/78734768-b1d9ca00-797b-11ea-9c3f-daf54493414b.png)
抱歉

**Comment by CodFrm** [comment]
哦,好的,我看一下

**Comment by MartyAlien** [comment]
好的，麻烦啦

**Comment by CodFrm** [comment]
确实有点问题,今天我更新一下

**Comment by MartyAlien** [comment]
辛苦啦！

**Comment by MartyAlien** [comment]
建议作者查看一个vx公众号：智慧的树知到免费答案     vx号是gh_cda42977f7c5
推荐的目的是：题库很全，因为今天我测试了一下，编译原理课程考试里面很多题小工具都没有，但是通过这个公众号能得出答案，但是麻烦的是需要输入题目去获取答案，看看作者方不方便去试试能不能调用调用接口

**Comment by CodFrm** [comment]
我这边已经有另外的题库再对接中了

**Comment by MartyAlien** [comment]
那行，仅做参考

**Comment by CodFrm** [comment]
已经修复,考试已经对接题库,可以试试准确率

**Comment by MartyAlien** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodFrm"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 下午5:47
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"Imp@tan"<monster8alien@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] 超星-考试版块题目上传问题 (#150)





 
已经修复,考试已经对接题库,可以试试准确率
