### ISSUE TITLE
建议加一个通知开关和网页上的弹窗提示开关

### ISSUE THREAD

**Issue by lhllhx** [CodFrm/cxmooc-tools#151]
我切一下网页就。。。
![TIM截图20200408173900](https://user-images.githubusercontent.com/52107206/78769370-dd7ea380-79bf-11ea-88c3-433df49e1b97.png)
这些通知对我这种老油条没什么用了

**Comment by wh4leF1ND3R** [comment]
如果你使用的是chrome浏览器,转到设置→消息提示(notification)→手动添加屏蔽的网站地址,如果你用的不是chrome浏览器,那就快去使用chrome浏览器

**Comment by CodFrm** [comment]
已经在弄了

**Comment by CodFrm** [comment]
你的是什么版本？最新的应该会通知3s关闭

**Comment by lhllhx** [comment]
插件是谷歌商店最新版本（v2.3.2） 谷歌浏览器是75.0.3770.100（正式版本） （64 位）
这个通知也建议加个开关
![TIM截图20200408202354](https://user-images.githubusercontent.com/52107206/78783876-e75fd100-79d6-11ea-81e9-8c600c537734.png)

**Comment by CodFrm** [comment]
emmm ui 还想优化
![image](https://user-images.githubusercontent.com/22783163/78993736-f7131d00-7b70-11ea-852d-e2ac9855cb52.png)
