### ISSUE TITLE
关于近期(4/8/20)智慧树平台弹出公告表示"使用作弊现象会上报处罚"类内容,有没有做过反上报的调查或者措施

### ISSUE THREAD

**Issue by wh4leF1ND3R** [CodFrm/cxmooc-tools#152]
我大致对比了一下前后网页内容没有找到明显的特征和改动,推测可能会利用cookie统计用户的在线真实情况,如果情况属实,对此有没有什么反制措施?

**Comment by CodFrm** [comment]
没有看见智慧树有上报机制，那个只是一个通知你的而已

**Comment by wh4leF1ND3R** [comment]
> 没有看见智慧树有上报机制，那个只是一个通知你的而已

这样啊,我懂了
