### ISSUE TITLE
mooc课后讨论复读机功能

### ISSUE THREAD

**Issue by cj1916** [CodFrm/cxmooc-tools#153]
只要打开课后讨论的页面，插件就会复读，不管是否已完成，多次进入就会有多次复读
建议：添加一个识别功能，已经完成讨论的自动跳过，不会多次复读

**Comment by CodFrm** [comment]
但是没有看见有标志表明已经复读过了

**Comment by cj1916** [comment]
已经复读过的会有已关注的字样
![IVO ZPLV%LNTJ$8$104NME](https://user-images.githubusercontent.com/61930443/78849267-91c30d00-7a46-11ea-9380-a8aa414aeee3.png)

**Comment by CodFrm** [comment]
好的

**Comment by cj1916** [comment]
大佬牛逼，辛苦
