### ISSUE TITLE
建议新增功能——'爬题入档'

### ISSUE THREAD

**Issue by MartyAlien** [CodFrm/cxmooc-tools#155]
### 功能描述
> 需要实现的功能的阐述
其实这个功能主要是针对已做过的题，包括测验，考试，作业，小试牛刀等题，将这些已做过的题按照用户的需要，询问用户是否打包至本地Excel或word文档存储，由于本插件好像无法应对课堂的随机测验试题，我的建议是，通过插件读取本地已经打包好的题目文件，对随机测验进行作答，其实不仅如此，在考试或者是其他情况下，插件优先访问用户本地题库，也可以减小服务器的访问压力，我也从讨论群中得知服务器中的题只是题库中的部分这样做是为了减少服务器的花费，但是在一定程度上缩小了用户体验，那么我想，通过打包题目至用户本地、从用户本地读取题目到作答页面，在一定程度上可以减少用户查无此题的情况，因为冷启动需要时间，在做一些作答时间很短的测验的时候，可能冷启动作用不是很大。
以下是功能大概的说明：
>该功能可作为一个开关，由用户决定使用与否
>使用的情况下，可由用户指定打包文件存储地址，相应的读取地址也随之改变
>爬取题目做到同一次测验不多次爬取
>打包的题目做到可读写，用户可以再里面做题目更改，增强题目的准确性
>应对随机测验等可优先访问用户本地已打包的题库

上述功能仅做参考，其实这款插件做得很好，不管是在速度上和准确性上都堪称一绝，其实我的意思很简单就是把每个用户机当成是小型服务器...

**Comment by CodFrm** [comment]
用户机当小型服务器是不可能的事情,用户机我想大多都是没有公网ip的,光这一点就不可能做到.

> 课堂的随机测验试题
这个是 https://github.com/CodFrm/cxmooc-tools/issues/142 这个么?如果是,我这边已经有解决方案,但是时间少就,优先级排低

打包本地题库,太麻烦了,我需要写一个本地爬虫,去遍历所有的课程,还可能影响到检测访问频繁=_=....其次答案还是需要从服务器获取...

而且不同用户直接的使用,难道就靠线下(qq)交流,发你题库,不太可能

其实服务器的资源利用率现在还算好.
