### ISSUE TITLE
音频录播加速

### ISSUE THREAD

**Issue by NewbeBrynbo** [CodFrm/cxmooc-tools#156]
背景：
依赖于[x.chaoxing.com]，进行手机投屏。在直播过程中可以交互式查看PPT目录并切换，发放签到时可以在本地查看签到名单，会动态更新。我还真没见过几个这样搞的...

问题描述：
每一页PPT保留在此页面停留时间长度的音频，可以通过目录或者切换页面把录播刷过去，不过任务点没找到在哪设置的，保险起见想加速处理。

需求描述：
对每一页音频都进行倍速播放。

用变速齿轮测试了一下失败了，求大大check一波

示例网址如下：（感觉这样不太妙，仅作测试orz..
[http://apps.wh.chaoxing.com/screen/vclass/view/1e74567fd2a0486e8800b65489a5575f]

**Comment by CodFrm** [comment]
![image](https://user-images.githubusercontent.com/22783163/78999615-950ce480-7b7d-11ea-8f81-3df8377315af.png)

应该直接修改这个audio的倍速就行了,这种页面我不可能弄- -.... 如果你有兴趣的话..可以给插件提交pr
