### ISSUE TITLE
题目无法更新到数据库

### ISSUE THREAD

**Issue by 709519923** [CodFrm/cxmooc-tools#158]
**错误描述**
中国大学mooc无法更新题库

**错误提示和日志内容**
出现做了错题之后，第二次做还是一样地搜索不到答案
**出现时间**
4.13.2020

**错误版本**
Chrome，插件，最新版本2.3.3

**Comment by CodFrm** [comment]
截图看一下,可能是有特殊的内容没有处理

**Comment by CodFrm** [comment]
最好给出题目的链接
