### ISSUE TITLE
题库错误反馈&更新

### ISSUE THREAD

**Issue by CodFrm** [CodFrm/cxmooc-tools#16]
已经收集了5000多条题目了 ^_^ 看来使用者还是挺多的

以后就把题库备份传到这里吧,如果有错误的答案也可以在这里反馈

[answer.zip](https://github.com/CodFrm/cxmooc-tools/files/2037748/answer.zip)

2018/11/15
34063条

**Comment by CodFrm** [comment]
题库json

[answer.zip](https://github.com/CodFrm/cxmooc-tools/files/2075935/answer.zip)

**Comment by 98line** [comment]
可否联系我一下，我有题库答案，可以发送予你可以吗？谢谢大神！
[尔雅.最新军事理论课后答案%28同济版%29.docx](https://github.com/CodFrm/cxmooc-tools/files/2087147/28.29.docx)

**Comment by CodFrm** [comment]
@98line 说得太客气了

问题是我还没写导入的,后面再写
![7650c95530fe3e713a5ef54c3454940c](https://user-images.githubusercontent.com/22783163/41197838-91bc22ba-6c9c-11e8-8dd1-50dcd4224311.jpg)

**Comment by 98line** [comment]
编程我还啥的不懂，不过有需要答案什么的，我可以帮忙，主要想了解一下现阶段会自动进入下一节课程吗？提交答案的时间间隔是多少，我试过另一款挺不错的，但间隔太久了二十分钟，可是最近好像崩了谢谢大神了！辛苦你了

**Comment by CodFrm** [comment]
@98line 会实现自动下一节课程....但是什么时候去弄还不太清楚,最近有些其他的东西要写,希望这个月能完成

**Comment by 98line** [comment]
辛苦了辛苦了！谢谢大神

**Comment by 98line** [comment]
辛苦了辛苦了！谢谢大神

**Comment by seven-out** [comment]
大大怎么加入这个项目   想学习学习

**Comment by CodFrm** [comment]
@seven-out 下载源码，修复bug/增加/完善功能就好了，虽然我代码写得很糟，看起来很乱:sob:

**Comment by yunyi1598** [comment]
九月八日1.5的开始挂机已经不起作用了。作者还维护这个插件嘛0.0

**Comment by CodFrm** [comment]
@yunyi1598 好像是的。。。变换成h5的播放器了

快毕业了，暂时没有更新的打算

**Comment by yunyi1598** [comment]
> @yunyi1598 好像是的。。。变换成h5的播放器了
> 
> 近期有一个小更新的打算

好的，谢谢大佬

**Comment by jiangzhiwei2018** [comment]
大佬，你发的题库我下不下来是什么原因，网页崩了？

**Comment by CodFrm** [comment]
@jiangzhiwei2018 网络的问题吧。。。。你是说的那个题库？这个页面的题库都是数据库的形式

**Comment by qq982085295** [comment]
> 已经收集了5000多条题目了^ _ ^看来使用者还是挺多的
> 
> 以后就把题库备份传到这里吧，如果有错误的答案也可以在这里反馈
> 
> [answer.zip](https://github.com/CodFrm/cxmooc-tools/files/2037748/answer.zip)

请问大佬 这个题库如何导入呢

**Comment by CodFrm** [comment]
> > 已经收集了5000多条题目了^ _ ^看来使用者还是挺多的
> > 以后就把题库备份传到这里吧，如果有错误的答案也可以在这里反馈
> > [answer.zip](https://github.com/CodFrm/cxmooc-tools/files/2037748/answer.zip)
> 
> 请问大佬 这个题库如何导入呢

这是数据库的，如果从数据库中搜索到了答案，会自动填入

**Comment by qq982085295** [comment]
> > > 已经收集了5000多条题目了^ _ ^看来使用者还是挺多的
> > > 以后就把题库备份传到这里吧，如果有错误的答案也可以在这里反馈
> > > [answer.zip](https://github.com/CodFrm/cxmooc-tools/files/2037748/answer.zip)
> > 
> > 
> > 请问大佬这个题库如何导入呢
> 
> 这是数据库的，如果从数据库中搜索到了答案，会自动填入

好的 多谢 辛苦了

**Comment by moshiyeap** [comment]
希望能贡献绵薄之力 虽然我可能是假的计科生，但是我可以帮忙写文档。。。

**Comment by CodFrm** [comment]
@moshiyeap _(:зゝ∠)_欢迎pr

**Comment by messiisgod** [comment]
我这里有论坛淘来的很全的智慧树的答案，不知道能不能帮到大佬
链接: https://pan.baidu.com/s/1_vWEL9-FZwqk6DCf_da4UA 提取码: ncyk

**Comment by whilepy** [comment]
大佬 ，能不能做一个通过已经完成题目的页面中提取正确答案的功能，这样录答案快捷还准确

**Comment by CodFrm** [comment]
@whilepy 有的

**Comment by jiongsbfanjian** [comment]
大佬，请教一下，这个题库json怎么用

**Comment by DarkOfXFL** [comment]
[https://www.jb51.net/softs/627948.html](url)
Tampermonkey油猴的尔雅在线刷课脚本（就是广为流传的“娜娜刷课 后台挂尔雅浏览器”），希望多少能提供一点直接的帮助（把前人的功能集成起来），目测现在油猴脚本的在线题库功能能用，答案精准度非常高，现在我两个一起开，禁止“全自动挂机”，然后只单点“开始挂课”，挂完一节课后自动答卷，90%精准度的答题质量（如果开了全自动挂机，会随机答题，居然连续出现了零分卷，吓得我不敢再开全自动……），就是因为没开全自动，不能自动跳到下一节课……

**Comment by CodFrm** [comment]
@DarkOfXFL 感谢，它的题库确实很完善_(:зゝ∠)_。。。跳到下一节已经修复。

**Comment by DarkOfXFL** [comment]
已经找到了（终于找到了）娜娜刷课脚本有时不灵的原因，就是它要下载一个超大的JS脚本，文件名为："allcontroller.min.js"，大小居然达到了39.1KB（目前来看是这样的），而且每次转跳到答题界面时都要从"freejs19.nanayun.com"这个域名重新下载下来，这样做会导致很多人用的话，服务器负荷很大（也不算大啦，随随便便一个好看点的HTML都要几百KB了），但是这个"nanayun.com"域名在中国里面是没有备案的，直接访问会导致被中国DNS重定向到DNSPOD拦截提示页要求备案，我翻墙出去测试了一下，可能由于内网太渣依然会出现加载不出来的情况，索性把它下载下来保存到本地，架设本地HTTP服务器，把脚本里的请求转移到本地，问题得到解决（目前测试感觉非常可靠，每次到答题的时候都能加载出来）。

您的插件可以实现鼠标离开视频框而不暂停的挂机功能，但不能识别任务点已完成的情况，自动跳转功能不及娜娜刷课厉害，题库功能太过薄弱，经常经常搜不到题目，娜娜刷课的不暂停视频功能失效，但题库功能依旧可用，而且基本上没遇到过搜不到题的情况，答题准确率90%以上。由于您的插件实现了最核心最重要的功能，还是必须怒赞的，而娜娜刷课方面，人家已经不更新了，还搞起了代刷代挂的生意（如果深究后果不堪设想，毕竟进行了经济活动）。之前我说的是我同时开了大佬您的插件和油猴脚本（娜娜刷课），用您的插件负责视频不暂停功能（开启“全自动挂机 + 随机答题”，如果不开随机答题会弹出JavaScript里的alert提示框并暂停当前网页后续代码的执行，需要手动点击确认消掉提示框才能继续执行其它代码，所以无人看守的话会导致挂机中断，如果开了随机答题，尽管一开始会随机答题，但后面 娜娜刷课脚本也会进行自动答题，覆盖掉之前的随机答案），娜娜刷课负责判断任务点完成情况并自动跳转，以及高准确度的答题功能。之前说“如果不开启 全自动挂机 ，会不能转跳到下一个任务点”，那是因为我发现开启娜娜刷课脚本里的自动跳转功能不奏效，后来发现是QQ浏览器的深度定制的谷歌内核兼容性造成的BUG，换成谷歌浏览器（翻墙到官网下载的，绝对是真家伙）就一点问题都没有。

目前插件设置情况：慕课小工具（开启“随机答案”和“全自动挂机”，间隔时间设置成3分钟以确保留给娜娜刷课脚本有足够时间自动答题），娜娜刷课脚本（脚本关键设置："video: 1 ,work: 1 ,jump: 1 ,test: 1"，好像一开始的默认设置就是这样的唉，自己手残改了参数进行测试，各位可千万别学我啊！ ）

我呢，就是个还在C语言挣扎而对高级语言莫名恐惧的 大学渣渣程序员，JAVA领域怕水深（JAVA经常更新函数用法，个人感觉太激进，但也因为如此而强大优秀）怕用了收费代码，习惯了C语言灵活的语法（重点是比较接近底层，我自学单片机非常需要它，然后指针大法真的是厉害）无法自拔，蓝瘦……所以现在大佬您的高度我是难以企及的，现在还在攻克心理障碍去接受高级语言，在此共勉。

**Comment by DarkOfXFL** [comment]
抱歉，娜娜刷课脚本在稳定答完4节课的题目后，本地保存的"allcontroller.min.js"失效，表现为无法请求到正确答案，提示你下载最新版的娜娜刷课浏览器。我还是想想怎么加速访问吧，毕竟题库被掌握在“娜娜云”里……蓝瘦……

**Comment by CodFrm** [comment]
@DarkOfXFL 

识别任务点完成，我懒得去弄了。。。下一次我会考虑弄进去的

原来是想直接用娜娜的题库，但是怕又有问题，它突然停掉之类，和自己也想做一个题库，然后就自己写了一个题库的功能- -。。。还有想学习新技术的想法在里面

后面吹得我不好意思了。。。。各有优势，原来我也想学单片机的，但是用C学了个流水灯之后就没搞了

**Comment by LUBIXUAN** [comment]
大佬，非常感谢你的程序，最近刷课弄了好久都不能自动下一节，是出了什么问题了吗

**Comment by CodFrm** [comment]
@LUBIXUAN 你的是那种不刷完一节不会解锁的那种吗？

**Comment by LUBIXUAN** [comment]
我能加你联系方式吗，我微信18291909087，很需要你的帮助，可以打赏

**Comment by LUBIXUAN** [comment]
对的，不刷完不解锁，有什么解决办法吗

**Comment by CodFrm** [comment]
@LUBIXUAN 已经解决了，但是还没发布

**Comment by CodFrm** [comment]
@LUBIXUAN 发了，你可以试试

**Comment by LUBIXUAN** [comment]
辛苦了，谢谢

**Comment by LUBIXUAN** [comment]
大佬，不行啊，这个版本情况是这样的，鼠标移开视频，就停止了。然后视频停了就不会继续了。点击章节检测，题目自动做完。也会暂时跳到下一个视频，但是，还像是下一个视频还未解锁然后又跳回来了。调回来。目录跳回来之后下一视频才解锁。嗯具体情况是这样，感谢大佬的努力，相信会有更多人关注你的作品。

**Comment by boy1024** [comment]
@CodFrm 
- [选择方法二下载的Chrome插件
设置了随机答案和自动挂机2分钟
版本1.5.3出现我测试的出现以下问题：
视频中的问题答案不能自动提交
随机答案选择后不能自动提交
手动提交答案以后，视频不能自动播放到下一个

**Comment by CodFrm** [comment]
@boy1024 之前的版本有出现吗？

**Comment by boy1024** [comment]
之前的版本视频播放完不能自动播放到下一个
我试了一下把三个插件都安装上
依旧出现以上问题
还有就是用娜娜插件和您的插件一起用
唯一缺点就是娜娜题库时好时坏
而您的插件的核心功能播放完毕不能转到解题界面

**Comment by CodFrm** [comment]
@boy1024 f12 提供一下console截图页面也一起，我看看

**Comment by boy1024** [comment]
![2018-10-17 11 01 13](https://user-images.githubusercontent.com/40294654/47059520-471f5680-d1fc-11e8-9f13-0f8a1c584ac0.png)
![2018-10-17 11 01 19](https://user-images.githubusercontent.com/40294654/47059521-47b7ed00-d1fc-11e8-9ab3-dc34a6d8bb5c.png)
![U
![2018-10-17 11 01 23](https://user-images.githubusercontent.com/40294654/47059522-48508380-d1fc-11e8-9282-71a1dde78c23.png)

**Comment by boy1024** [comment]
其他问题还好，主要是这个bug让我很难受
![2018-10-17 11 06 02](https://user-images.githubusercontent.com/40294654/47059670-f65c2d80-d1fc-11e8-973d-fb3589f16fd8.png)

**Comment by lizhihao6** [comment]
https://blog.csdn.net/pengchangsi5470/article/details/62885254
嘿，可以加入这个题库吗？

**Comment by luojunyuan** [comment]
[像经济学家1.txt](https://github.com/CodFrm/cxmooc-tools/files/2492997/1.txt)
[像经济学家2.txt](https://github.com/CodFrm/cxmooc-tools/files/2492999/2.txt)
[像经济学家3.txt](https://github.com/CodFrm/cxmooc-tools/files/2493000/3.txt)
三个题库，感谢farmer百忙之中添加

**Comment by huangketuan** [comment]
方法二下载的Chrome插件版本1.5.3
设置了随机答案和自动挂机5分钟
出现问题是：程序未自动选择提交答案，问题界面持续存在，但视频继续播放着，这样没有提交答案会被检测出来吗？

**Comment by CodFrm** [comment]
> 方法二下载的Chrome插件版本1.5.3
> 设置了随机答案和自动挂机5分钟
> 出现问题是：程序未自动选择提交答案，问题界面持续存在，但视频继续播放着，这样没有提交答案会被检测出来吗？

暂时是这样的，我不确定会被检测，后面我会修复这个问题

**Comment by huangketuan** [comment]
> > 方法二下载的Chrome插件版本1.5.3
> > 设置了随机答案和自动挂机5分钟
> > 出现问题是：程序未自动选择提交答案，问题界面持续存在，但视频继续播放着，这样没有提交答案会被检测出来吗？
> 
> 暂时是这样的，我不确定会被检测，暂时来看是没问题的，后面我会修复这个问题

还发现一个问题，就是当同一页面存在视频任务和作业答题任务的时候，自动挂机是不能自动进入下一个视频的

**Comment by huangketuan** [comment]
> > > 方法二下载的Chrome插件版本1.5.3
> > > 设置了随机答案和自动挂机5分钟
> > > 出现问题是：程序未自动选择提交答案，问题界面持续存在，但视频继续播放着，这样没有提交答案会被检测出来吗？
> > 
> > 
> > 暂时是这样的，我不确定会被检测，暂时来看是没问题的，后面我会修复这个问题
> 
> 还发现一个问题，就是当同一页面存在视频任务和作业答题任务的时候，自动挂机是不能自动进入下一个视频的

 还发现一个问题，就是带有弹幕的那种播放器的视频播放不了，您有空是否能修复一下，谢谢！

**Comment by CodFrm** [comment]
@huangketuan 弹幕的播放器没测试案例，暂时没打算

**Comment by huangketuan** [comment]
> @huangketuan 弹幕的播放器没测试案例，暂时没打算

action.js 文件下代码：
if (!(Ext.isIpad || Ext.isIos || Ext.isAndroid)) {
改为：
if ((Ext.isIpad || Ext.isIos || Ext.isAndroid)) {
直接使用showHTML5Player(paras)
就可以了

**Comment by huangketuan** [comment]
> @huangketuan 弹幕的播放器没测试案例，暂时没打算

@CodFrm 我修改了action.js文件下代码：
if (!(Ext.isIpad || Ext.isIos || Ext.isAndroid)) {
改为：
if ((Ext.isIpad || Ext.isIos || Ext.isAndroid)) {
直接使用showHTML5Player(paras)
就可以了

**Comment by CodFrm** [comment]
@huangketuan 真的吗？我没遇到有弹幕的情况，你可以发一个pr

**Comment by CodFrm** [comment]
@huangketuan 想起来了，这是为了原来适配flash播放器的版本，我没有把这些代码删除

**Comment by huangketuan** [comment]
> @huangketuan 想起来了，这是为了原来适配flash播放器的版本，我没有把这些代码删除

@CodFrm 嗯嗯，非常感谢你的代码！

**Comment by gd-dongzai** [comment]
视频里的题目好像无法自动完成，自动挂课不会给后台检测到的吧，一开始的几个章节用秒过给记录了一次不良记录，有点慌

**Comment by CodFrm** [comment]
@gd-dongzai 视频里面的题目不完成问题不大，秒过的话被检测到是不可逆的

**Comment by ewng** [comment]
> 视频里的题目好像无法自动完成，自动挂课不会给后台检测到的吧，一开始的几个章节用秒过给记录了一次不良记录，有点慌


> @gd-dongzai 视频里面的题目不完成问题不大，秒过的话被检测到是不可逆的

只用了一次就在首页提示不用使用辅助工具的警告。这有什么后果吗？

**Comment by CodFrm** [comment]
@ewng 
暂时不知道，只是提示警告，看学校吧，我们学校对这个并不怎么管

**Comment by huangketuan** [comment]
@CodFrm 看了你的更新，修正了播放器和包含视频与试题的页面无法完成跳过的问题，其实还有个问题：你的video.js里的框架iframe和任务点ans使用了共同传入参数index，当页面中的iframe与ans不一致的时候就会出错了，比如第一个iframe里嵌入的是非任务性的ppt

**Comment by CodFrm** [comment]
@huangketuan 好的，谢谢，有时间我再看看

**Comment by huangketuan** [comment]
> @huangketuan 好的，谢谢，有时间我再看看

之前我利用iframe的地址规律，通过循环iframes[i].src.indexOf('/video/')，重新找视频框架iframe的index，稍微修复了一下这个问题

**Comment by timef1yer** [comment]
我朋友被警告了耶

**Comment by luojunyuan** [comment]
> 我朋友被警告了耶

如果你使用了秒过视频功能被警告作弊，在某一时间后台会发送所有没有观看满对应视频时长的视频数目到所在学校数据库。
你可以重新把跳过的视频看一遍，大概率消除该记录

**Comment by RealCorebb** [comment]
可以麻烦把这个加进去吗？我用题库导入设置好了，也能匹配得到，但是在网络课里面搜不到，不知道为什么。
[声光影的内心感动：电影视听语言(超星网络课).docx](https://github.com/CodFrm/cxmooc-tools/files/2553246/default.docx)

**Comment by pinkpeachabc** [comment]
您好，能麻烦您把这个加入进去吗？ 本地测试成功也可以匹配的到，搜索答案显示未搜索，不知道原因。 拜托了！
[超星泛雅——大学生心理健康教育(2017版)(答案).docx](https://github.com/CodFrm/cxmooc-tools/files/2565363/2017.docx)
’

**Comment by kangvcar** [comment]
[用经济学智慧解读中国2018尔雅答案完整版.pdf](https://github.com/CodFrm/cxmooc-tools/files/2642854/2018.pdf)
我也来做贡献啦

**Comment by lengthmin** [comment]
你好，不是很懂如何贡献答案？
能否再说明一下。。

**Comment by Ch4osMy7h** [comment]
大佬能不能提供下目前最新的搜集到的答案嘛

**Comment by CodFrm** [comment]
> 大佬能不能提供下目前最新的搜集到的答案嘛

前面有比较新的，有标注日期

**Comment by lengthmin** [comment]
看了下代码 貌似并没有发现把做对的题传到服务器上的功能呀

**Comment by CodFrm** [comment]
> 看了下代码 貌似并没有发现把做对的题传到服务器上的功能呀

在这里，代码有点乱。。。=_=当初写没想太多。。。现在也没什么时间去重构了
[https://github.com/CodFrm/cxmooc-tools/blob/master/src/cxmooc-tools/topic.js#L132](https://github.com/CodFrm/cxmooc-tools/blob/master/src/cxmooc-tools/topic.js#L132)

**Comment by ithg** [comment]
逛脚本时 突然找到了这个站 http://www.92daikan.com/tiku.aspx
试了一下 绝大部分题都可以查到 可以接入（慢慢爬）
