### ISSUE TITLE
火狐能搜到答案，而chrome不能

### ISSUE THREAD

**Issue by JoeyDu-coding** [CodFrm/cxmooc-tools#162]
chrome中搜索答案有时刚开始显示搜索不到，但停一段时间或者做几个题之后再搜才搜到答案，而别人的火狐中可以搜到答案，这是什么呢？

**Comment by CodFrm** [comment]
题库太大了,所以优先缓存使用率高的题库,点击搜索如果没搜到，会从冷数据库中查询 并保存到主数据库,所以中间有延迟,如果题库命中次数低 就会被逐渐冻结 直到下一次被读取
