### ISSUE TITLE
这种类型的无法自动刷课

### ISSUE THREAD

**Issue by 1010joymo** [CodFrm/cxmooc-tools#164]
![反馈](https://user-images.githubusercontent.com/62790706/79529028-2b6d6880-809e-11ea-80aa-c627da7ac083.png)

**Comment by CodFrm** [comment]
你的插件版本是多少?

**Comment by 1010joymo** [comment]
2.3.3

**Comment by CodFrm** [comment]
刷新一下页面试试,这种视频类型应该是已经支持了的

**Comment by CodFrm** [comment]
而且...我好像也没有看见插件加载成功的迹象

**Comment by 1010joymo** [comment]
我把那个小工具通知条暂时关闭了，我遇到的问题是视频需要手动播放，播放也需要手动静音，不会自动跳到下一个视频播放。

**Comment by CodFrm** [comment]
给出你的配置选项....如果刷新页面不可以的话,方便给一下账号信息,我去调试一下

love@xloli.top 我的邮箱,或者加群,qq联系也可以

**Comment by 1010joymo** [comment]
![image](https://user-images.githubusercontent.com/62790706/79529530-818edb80-809f-11ea-8173-10adaf90ec98.png)

**Comment by 1010joymo** [comment]
![image](https://user-images.githubusercontent.com/62790706/79529598-a3885e00-809f-11ea-8b65-779f62caff8c.png)

**Comment by CodFrm** [comment]
请开启超级模式,这种视频需要超级模式的支持  

http://cx.icodef.com/1-UserGuide/1-4-config.html#%E8%B6%85%E7%BA%A7%E6%A8%A1%E5%BC%8F

**Comment by 1010joymo** [comment]
okok，万分感谢。
