### ISSUE TITLE
问一下使用秒过视频会有什么后果？

### ISSUE THREAD

**Issue by xuedong97** [CodFrm/cxmooc-tools#165]
提示说会有不良记录，会有什么不良记录呢

**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
老师能在后台查到你的观看记录,如果发现异常就看你们老师怎么处理了.

如果出现不良记录,超星官方在两次不良记录后会采取封号冻结的措施
