### ISSUE TITLE
检测到第三方脚本

### ISSUE THREAD

**Issue by Sun-ZhenXing** [CodFrm/cxmooc-tools#168]
MOOC专用Google浏览器答题的时候自动搜索答案会出现提示检测到第三方脚本
请问有没有解决办法，可以防止被监控到，或者MOOC是用什么方式（监听用户的事件、行为）发现第三方脚本的

**Comment by CodFrm** [comment]
是mooc专用那个浏览器？

**Comment by CodFrm** [comment]
我这里没有出现,重启浏览器,看一下插件版本是否正确 2.4.3+
