### ISSUE TITLE
从网上提取的刷课浏览器js插件 远程加载js 做到视频挂机（不出问题） 以及题库查询

### ISSUE THREAD

**Issue by fuergaosi233** [CodFrm/cxmooc-tools#17]
https://github.com/fuergaosi233/chaoxingshuake
远程加载代码的js 在background.js文件中
代码混淆了  希望会有帮助

**Comment by CodFrm** [comment]
好的,感谢分享,我有时间去看看

**Comment by CodFrm** [comment]
@fuergaosi233 
看了一下,和我之前想过的一个方法差不多,修改了播放器,很厉害....
我没试过,觉得有些做不到,那天尝试一下不(不行偷他代码?逃)

**Comment by CodFrm** [comment]
已经自己尝试反编译flash成功,后面差不多也可以做成他的效果了
