### ISSUE TITLE
建议增加学习通自动提交题目的功能

### ISSUE THREAD

**Issue by Jontyshaw** [CodFrm/cxmooc-tools#170]
学习通刷视频总是播放完当前的卡在章节测验题目的提交上，建议增加章节测验题目自动提交的功能

**Comment by CodFrm** [comment]
?应该是有的,提供一下截图/视频之类的看看

**Comment by Jontyshaw** [comment]
> ?应该是有的,提供一下截图/视频之类的看看

这是图片
![2020-10-20-195718_1920x1080_scrot](https://user-images.githubusercontent.com/34794522/96583043-b873d180-130e-11eb-94c7-57dd0241300c.png)
![2020-10-20-195732_1920x1080_scrot](https://user-images.githubusercontent.com/34794522/96583058-bb6ec200-130e-11eb-8f16-19eac346b80d.png)

**Comment by CodFrm** [comment]
你有没有等间隔时间....
![image](https://user-images.githubusercontent.com/22783163/96812838-e3653f00-144e-11eb-8490-ad4365ed8a56.png)

**Comment by Jontyshaw** [comment]
设置好间隔时间正常了，谢谢
