### ISSUE TITLE
1.4.0版本视频播放框是黑的，没有任何东西

### ISSUE THREAD

**Issue by lovetears** [CodFrm/cxmooc-tools#18]
![_20180602221438](https://user-images.githubusercontent.com/21056242/40877435-66d83280-66b3-11e8-98ef-0a83cc31aeee.png)
求修复

**Comment by CodFrm** [comment]
@lovetears 刚刚增加了服务器缓存,你再试试看看有没有出现?

**Comment by lovetears** [comment]
@CodFrm 还是一样，依旧黑屏

**Comment by CodFrm** [comment]
@lovetears 你能访问这个网站吗?
[https://blog.icodef.com:8081/](https://blog.icodef.com:8081/)

**Comment by lovetears** [comment]
@CodFrm 可以的没有任何问题

**Comment by lovetears** [comment]
@CodFrm 刚刚又重新安装了一遍，莫名其妙的好了，谢谢了

**Comment by CodFrm** [comment]
@lovetears 没关系,因为1.4用了修改的播放器,第一次需要加载所需要的时间长一点,不知道你前面有没有等待,总之好了就行(๑•̀ㅂ•́)و✧
