### ISSUE TITLE
你好，插件的题库不足，总有搜不到题的情况，我有一个很全的题库，但是我不会把它和自动搜题建立联系[BUG]

### ISSUE THREAD

**Issue by HuiCan841** [CodFrm/cxmooc-tools#183]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

### 出现时间
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by HuiCan841** [comment]
你好，插件的题库不足，总有搜不到题的情况，我有一个很全的题库，但是我不会把它和自动搜题建立联系

**Comment by HuiCan841** [comment]
你这个脚本搜不到的时候我就用划词搜题插件，官网是www.zaixiantiku.com作者要是能把题库和这个网站建立联系就最好了，感谢大佬。

**Comment by CodFrm** [comment]
插件并不希望提供过多的题库,你可以修改代码进行切换

https://github.com/CodFrm/cxmooc-tools/blob/master/src/internal/app/question.ts#L152
