### ISSUE TITLE
[BUG]在Firefox浏览器智慧考试页面使用答题功能是显示出现致命错误

### ISSUE THREAD

**Issue by QCEEE** [CodFrm/cxmooc-tools#187]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
![图片](https://user-images.githubusercontent.com/68200335/101326495-52381380-38a8-11eb-8be9-dd5a0b6354e7.png)

### 错误提示和日志内容
> 出现致命错误

### 出现时间
> 打开智慧树考试页面

### 使用环境
> 火狐

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
什么版本?

**Comment by QCEEE** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodFrm/cxmooc-tools"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 下午4:24
收件人:&nbsp;"CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送:&nbsp;"-1"<1003178580@qq.com&gt;;"Author"<author@noreply.github.com&gt;;


主题:&nbsp;Re: [CodFrm/cxmooc-tools] [BUG]在Firefox浏览器智慧考试页面使用答题功能是显示出现致命错误 (#187)





 
什么版本?

**Comment by CodFrm** [comment]
无可用信息
