### ISSUE TITLE
[BUG]智慧树考试无法搜题

### ISSUE THREAD

**Issue by StarchierOrb** [CodFrm/cxmooc-tools#188]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
![image](https://user-images.githubusercontent.com/22254453/101489769-64937980-399c-11eb-9bdd-998fa9ec4ca8.png)
拓展在考试页面不起作用，通知条也没出现

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)
无

### 出现时间
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)
进入任意智慧树的考试

### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?
Chrome 78 内核的360极速
Chrome拓展 v2.5.0

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
发一下这个的地址

**Comment by CodFrm** [comment]
无可用信息
