### ISSUE TITLE
能增加学习通自动下一题功能吗

### ISSUE THREAD

**Issue by ningzhi123** [CodFrm/cxmooc-tools#189]
### 功能描述
> 需要实现的功能的描述

### 支援信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
一直都有

**Comment by ningzhi123** [comment]
是需要设置吗，我使用需要我自己点下一题😓😓😓

---原始邮件---
发件人: "王一之"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 中午12:26
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送: "ningzhi123"<2262223779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189)




 
一直都有

**Comment by CodFrm** [comment]
默认设置就是自动的
![image](https://user-images.githubusercontent.com/22783163/102752681-e3c57c00-43a4-11eb-8210-d56b1c56912b.png)

**Comment by ningzhi123** [comment]
傻了。我考试需要我自己点

---原始邮件---
发件人: "王一之"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 下午3:55
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送: "ningzhi123"<2262223779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189)




 
默认设置就是自动的

**Comment by CodFrm** [comment]
emmmm考试的话,就是需要自己点的.都考试了就不能认真点么?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ningzhi123"<notifications@github.com&gt;; 
发送时间: 2020年12月21日(星期一) 下午4:00
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;; 
抄送: "王一之"<code.farmer@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189)





 傻了。我考试需要我自己点 
 
 ---原始邮件--- 
 发件人: "王一之"<notifications@github.com&amp;gt; 
 发送时间: 2020年12月21日(周一) 下午3:55 
 收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&amp;gt;; 
 抄送: "ningzhi123"<2262223779@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189) 
 
 
 
 
   
 默认设置就是自动的

**Comment by ningzhi123** [comment]
哈哈哈，想睡觉

---原始邮件---
发件人: "王一之"<notifications@github.com&gt;
发送时间: 2020年12月21日(周一) 下午4:01
收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&gt;;
抄送: "ningzhi123"<2262223779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189)




 emmmm考试的话,就是需要自己点的.都考试了就不能认真点么? 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "ningzhi123"<notifications@github.com&amp;gt;;  
 发送时间: 2020年12月21日(星期一) 下午4:00 
 收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&amp;gt;;  
 抄送: "王一之"<code.farmer@qq.com&amp;gt;; "State change"<state_change@noreply.github.com&amp;gt;;  
 主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189) 
 
 
 
 
 
  傻了。我考试需要我自己点  
   
  ---原始邮件---  
  发件人: "王一之"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年12月21日(周一) 下午3:55  
  收件人: "CodFrm/cxmooc-tools"<cxmooc-tools@noreply.github.com&amp;amp;gt;;  
  抄送: "ningzhi123"<2262223779@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题: Re: [CodFrm/cxmooc-tools] 能增加学习通自动下一题功能吗 (#189)  
   
   
   
   
     
  默认设置就是自动的
