### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by nm1298780355** [CodFrm/cxmooc-tools#190]
### 功能描述
> 需要实现的功能的描述

### 支援信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱
自动答题功能什么时候才能用啊。

个人邮箱niman2272@gmail.com

**Comment by CodFrm** [comment]
?????自动答题一直都有

**Comment by nm1298780355** [comment]
> ?????自动答题一直都有

那可能是题库不全吧，体育网课一直就没搜到过答案。
![FireShot Capture 005 - 学生学习页面 - mooc1-1 chaoxing com](https://user-images.githubusercontent.com/75579357/102740488-df8c6500-438a-11eb-98be-df751c76580d.png)
