### ISSUE TITLE
[BUG]mooc答题显示题库网络错误/windows+chrom

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [CodFrm/cxmooc-tools#193]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
![}X)JGM2723PVKOP$BOKMQ9Y](https://user-images.githubusercontent.com/59465493/103403948-f56d0780-4b8c-11eb-986e-d13fc22adf32.png)

### 错误提示和日志内容
>控制台只有警告，没有错误

### 出现时间
> 每次点击搜索题库都会出现

### 使用环境
> chrom

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
应该是当时题库负载太大了,宕机了
