### ISSUE TITLE
秒过视频是怎么实现的？不会被发现作弊吧？

### ISSUE THREAD

**Issue by ZeR0ll** [CodFrm/cxmooc-tools#2]

**Comment by CodFrm** [comment]
先说...会的...后台会有检测你的在线时间来判断,不过有的学校并未管这个,我们学校就是的- -....
所以这个功能还是要低调使用,可以用挂机模式,这个就不会了

实现方法就是在视频的最后会有一个视频观看完成的封包,我们模拟那个封包告诉服务器说我们看完了
