### ISSUE TITLE
chorme 安装扩展 显示错误

### ISSUE THREAD

**Issue by bupt-steven** [CodFrm/cxmooc-tools#20]
显示该扩展可能已经损坏

**Comment by CodFrm** [comment]
@bupt-steven 什么浏览器?什么提示?按照方法2试试?

**Comment by bupt-steven** [comment]
chorme，方案2和方案3都试过了，不行。。在QQ浏览器上试了过了。。

**Comment by CodFrm** [comment]
@bupt-steven 看了一下,使用方法2安装的,有一个错误,但是不影响正常的使用
![tim 20180605111331](https://user-images.githubusercontent.com/22783163/40953269-89032324-68b1-11e8-897d-77a27949eec5.png)
![tim 20180605111430](https://user-images.githubusercontent.com/22783163/40953283-9befd266-68b1-11e8-82a0-78b4c1f8d8fb.png)
