### ISSUE TITLE
[BUG] 服务器好像关了？

### ISSUE THREAD

**Issue by drinkal** [CodFrm/cxmooc-tools#200]
### 错误提示和日志内容

> [debug 21:55:12 ] Start document state: loading
> mooc.js?v=2.5:3 [info 21:55:13 ] 超星新窗口加载
> mooc.js?v=2.5:3 [debug 21:55:15 ] 题目信息 Object
> mooc.js?v=2.5:3 [debug 21:55:15 ] 答案查询 Array(3)
> mooc.js?v=2.5:3 [debug 21:55:15 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:55:15 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> mooc.js?v=2.5:3 [debug 21:55:18 ] 答案查询 Array(3)
> mooc.js?v=2.5:3 [debug 21:55:18 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:55:18 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> mooc.js?v=2.5:3 [warn 21:55:25 ] 请注意!最小化可能导致视频无法正常播放!允许切换窗口.
> t.Warn @ mooc.js?v=2.5:3
> 32Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
> mooc.js?v=2.5:3 [debug 21:56:34 ] 题目信息 Object
> mooc.js?v=2.5:3 [debug 21:56:34 ] 答案查询 Array(3)
> mooc.js?v=2.5:3 [debug 21:56:34 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:56:34 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> mooc.js?v=2.5:3 [debug 21:56:35 ] 答案查询 Array(3)
> mooc.js?v=2.5:3 [debug 21:56:35 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:56:35 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> mooc.js?v=2.5:3 [debug 21:56:36 ] 播放器配置 Object
> mooc.js?v=2.5:3 [debug 21:56:37 ] 题目信息 Object
> mooc.js?v=2.5:3 [debug 21:56:38 ] 答案查询 Array(4)
> mooc.js?v=2.5:3 [debug 21:56:38 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:56:38 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> mooc.js?v=2.5:3 [debug 21:56:39 ] 答案查询 Array(4)
> mooc.js?v=2.5:3 [debug 21:56:39 ] 题库返回 Object
> mooc.js?v=2.5:3 [error 21:56:39 ] 题库无法访问,请查看:https://cx.icodef.com/
> t.Error @ mooc.js?v=2.5:3
> DevTools 无法加载 SourceMap： 无法加载 https://mooc1-1.chaoxing.com/js/common/jquery.min.map: 的内容HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

### 使用环境
> Chrome

### 其它信息

希望尽快恢复！感谢

**Comment by CodFrm** [comment]
题库关闭了
