### ISSUE TITLE
我用的是谷歌浏览器插件，今天考试时刚点开考试就显示考试时间到自动提交了，查看答题情况发现只答了第一部分的题目。今天的两门考试都是如此，可提供账号。[BUG]

### ISSUE THREAD

**Issue by bffty** [CodFrm/cxmooc-tools#204]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

### 出现时间
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
会不会是答题速度影响的呢? 看一下未答的题目
