### ISSUE TITLE
[BUG]浮窗超出边界

### ISSUE THREAD

**Issue by FakeChHN** [CodFrm/cxmooc-tools#205]
[###](url) 错误描述
[好哥哥，小悬浮窗拖到这以后动不了了]
![截图](https://user-images.githubusercontent.com/79900333/109616931-bfd6a180-7b70-11eb-9949-a5a0d1c44516.jpg)

### 出现时间
拖着它，鼠标指针放在书签栏以上

### 使用环境
chrome

### 其它信息
页面链接：https://mooc1-1.chaoxing.com/mycourse/studentstudy?chapterId=151163810&courseId=216244385&clazzid=36057700&enc=f464cf9b518ccbd56d2f2a98a9251114
邮箱：fakechhn@163.com

**Comment by CodFrm** [comment]
https://github.com/CodFrm/cxmooc-tools/pull/186 这个pull有bug?

**Comment by FakeChHN** [comment]
也就下载没几天，Google应用商店里下载的2.5.1版本。我还在mooc里听课，确实mooc里限制了边界不让通知窗口超出浏览器窗口，这个我也不知道自己咋搞的...



在 2021-03-10 10:36:21，"王一之" <notifications@github.com> 写道：

az...... 好像限制了边界来着 什么版本那么?

**Comment by FakeChHN** [comment]
> az...... 好像限制了边界来着 什么版本那么?

也就下载没几天，Google应用商店里下载的2.5.1版本。我还在mooc里听课，确实mooc里限制了边界不让通知窗口超出浏览器窗口，这个我也不知道自己咋搞的...

**Comment by FakeChHN** [comment]
我...我把自己蠢哭了，mooc也成这样子了
![image](https://user-images.githubusercontent.com/79900333/111295507-68632600-8686-11eb-86c9-2484db1fc2d2.png)

**Comment by CodFrm** [comment]
啊这....有时间判断一下



发自我的iPhone


------------------ 原始邮件 ------------------
From: FakeChHN ***@***.***&gt;
发送时间: 03/16/2021, 18:36
To: CodFrm/cxmooc-tools ***@***.***&gt;
抄送: 王一之 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Reply:[CodFrm/cxmooc-tools] [BUG]浮窗超出边界 (#205)





 
我...我把自己蠢哭了，mooc也成这样子了

**Comment by SSmJaE** [comment]
> 我...我把自己蠢哭了，mooc也成这样子了
> ![image](https://user-images.githubusercontent.com/79900333/111295507-68632600-8686-11eb-86c9-2484db1fc2d2.png)

有没有开关过开发者工具？
