### ISSUE TITLE
[BUG]我使用的是火狐的拓展，在刷慕课课后小测的时候，还没有点击搜索答案就自动开始搜索了，搜索完以后拓展自己又搜索了一遍，每个题目都显示搜索成功，但是点击提交答案以后，发现只有部分的题目有答案，大部分的都没有填充上答案，导致分数很差。

### ISSUE THREAD

**Issue by lyygua** [CodFrm/cxmooc-tools#206]
### 错误描述
> 

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)
![QQ截图20210307192429](https://user-images.githubusercontent.com/56330230/110238269-b6d43e80-7f7b-11eb-8b5c-8f6210b7968e.png)

### 出现时间
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by CodFrm** [comment]
还没有点击搜索答案 自动搜索 应该是设置了 自动挂机导致的

部分的题目有答案 建议脚本答题完成后再检查一下

**Comment by CodFrm** [comment]
mooc增加了检测,暂时不会自动选答案了 手动点点吧   有时间再修复
