### ISSUE TITLE
[BUG]最新版本下，chrome浏览器油猴版，进入课程后一直显示“正在为您加载文件”，关闭插件后又正常了

### ISSUE THREAD

**Issue by xuedong97** [CodFrm/cxmooc-tools#209]
### 错误描述
进入课程后一直显示“正在为您加载文件”，关闭插件后又正常了

### 使用环境
> Chrome88.0.4324.190（正式版本） （64 位），油猴4.11，超星慕课小工具版本为当前最新。
### 其它信息
> 提问者联系邮箱：xuedong97@qq.com

![Snipaste_2021-03-10_18-52-46](https://user-images.githubusercontent.com/62776598/110619165-6efb2480-81d2-11eb-95ed-1c8f9421d006.png)

**Comment by CodFrm** [comment]
感觉是网络问题
