### ISSUE TITLE
[BUG]小窗口不能移动

### ISSUE THREAD

**Issue by simple7091** [CodFrm/cxmooc-tools#219]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

### 出现时间
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

### 其它信息
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱

**Comment by simple7091** [comment]
![图片](https://user-images.githubusercontent.com/60818521/115254008-875e4780-a15f-11eb-99aa-d87eeb70c89d.png)
火狐扩展，
弹出的窗口一直都无法移动，目前狐火浏览器版本为88.0（64位）
![图片](https://user-images.githubusercontent.com/60818521/115253857-5ed64d80-a15f-11eb-971e-fb858e5b5074.png)


> 
> 
> 需要更多信息，现有信息不足以判断

**Comment by CodFrm** [comment]
@simple7091 这是拖动的那个条被拖到无法点击的地方了么？

**Comment by simple7091** [comment]
> 
> 
> @simple7091 这是拖动的那个条被拖到无法点击的地方了么？

这个拓展，我蛮久之前就在用了。某次更新的吧，窗口可以正常移动，后面就突然不行了，并不是把窗口我移动那个位置的，是某次打开就是这个样子的，然后一直这个样子。
