### ISSUE TITLE
多账户疑问

### ISSUE THREAD

**Issue by GITHUBSBEST** [CodFrm/cxmooc-tools#226]
老哥是这样的,使用火狐浏览器登陆自己的账号情况下,再在火狐浏览器登陆同学账号是不允许的,还有换一个浏览器也不被允许.是一个ip只对应一个账号吗

**Comment by CodFrm** [comment]
你确定换了浏览器?不同浏览器是可以多个账号的 不知道你的不允许是怎么样的

**Comment by GITHUBSBEST** [comment]
老哥是这样的,谷歌和火狐登陆都是同一个账号,而微软自带浏览器是可以登陆不同账号的,但是这里是不是没有适配微软浏览器的插件,还有请教一下是不是就是只有谷歌,油猴和火狐适配呀

**Comment by CodFrm** [comment]
@GITHUBSBEST 新版本的Edge应该是可以的，不清楚你什么情况，应该和插件无关

**Comment by GITHUBSBEST** [comment]
是的老哥，我发现确实只要换浏览器就可以换个账号；
