### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ryerster** [CodFrm/cxmooc-tools#227]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
![image](https://user-images.githubusercontent.com/45166189/117560241-84030f80-b0be-11eb-89db-7b72a8d934b5.png)

### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

### 出现时间
> 上上周还可以用，今天再打开就不能用了

### 使用环境
>下载的专用浏览器版本
### 其它信息
> 无法打开文档，经常不出现插件的公告和在网页中不显示小窗和按钮，有小窗和按钮也搜不了题，不能静音不能自动播放有时题库会erro

**Comment by CodFrm** [comment]
服务器顶不住了...
