### ISSUE TITLE
[BUG]题库无法访问

### ISSUE THREAD

**Issue by llkhs** [CodFrm/cxmooc-tools#232]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图

### 错误提示和日志内容
> 错误提示：题库无法访问,请查看:https://cx.icodef.com/

### 出现时间
>5月份开始出现

### 使用环境
> Microsoft Edge 版本 90.0.818.56 +油猴, 插件版本2.5.1，网课站点：超星(http://i.mooc.chaoxing.com/)

#
 ![捕获](https://user-images.githubusercontent.com/51050409/117914516-181ae400-b316-11eb-96a2-d9fa630bece8.PNG)

**Comment by CodFrm** [comment]
被ddos了，等吧
