### ISSUE TITLE
[BUG]mooc和学习通运用脚本刷视频时，视频结束时有较大概率使电脑死机

### ISSUE THREAD

**Issue by dism20** [CodFrm/cxmooc-tools#237]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
电脑死机，无法进行操作，鼠标键盘全部失灵，只能强制重启### 错误提示和日志内容
> 有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

### 出现时间不定时出现
> 你是怎么操作出现的这个错误?能不能复现呢?(再次出现)
正常看视频，视频结束的瞬间电脑直接死机，有时候不会，
### 使用环境
> 你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?
Chrome版本 4.3.9.248（正式版本） （64 位） (Portable) (Chromium 86.0.4240.198)
chrome版本 87.0.4280.88（正式版本） （64 位）都不行
火狐也不行，用的打包版的浏览器也不行
### 其它信息版本
> 出现的页面链接和课程等信息,另外是否可以提供账号,可以在此处留下邮箱
1169740779@qq.com
我怀疑是电脑问题，

**Comment by CodFrm** [comment]
？？？这个。。应该不会是脚本导致的吧

**Comment by duanfark2** [comment]
啊这

**Comment by dism20** [comment]
没事了，是电脑驱动问题。我重置系统就好了。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月6日(星期二) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodFrm/cxmooc-tools] [BUG]mooc和学习通运用脚本刷视频时，视频结束时有较大概率使电脑死机 (#237)
