### ISSUE TITLE
1.4及1.42版本无法播放视频

### ISSUE THREAD

**Issue by Basileusautokrator** [CodFrm/cxmooc-tools#24]
**错误描述**
没有启用扩展程序时视频照常播放，启用后视频播放器黑屏
**错误提示**
有没有错误的提示,没有不填写

**出现时间**
六月五日凌晨还能正常使用，现在（六月八日凌晨12点）无法使用

**错误版本**
Chrome:66.0.3359.181
扩展程序：1.4及1.42

**Comment by CodFrm** [comment]
@Basileusautokrator 黑屏的话 你看看这个网站能不能访问   https://blog.icodef.com:8081

**Comment by CodFrm** [comment]
行吧。。。。我也不能访问了，看来又得换服务器了   一口老血:sob:

**Comment by young-zy** [comment]
似乎是你的8081端口没有回应？检查一下你的nginx和防火墙配置，你的博客依旧可以正常访问。ps：可以考虑把这个资源文件放在更靠谱的地方（比如github）

**Comment by 414437542** [comment]
1.4及1.42打开视频直接黑屏，下面的换线路的选项出不来

**Comment by CodFrm** [comment]
@young-zy 是的....连接用github的好了,虽然github貌似也不稳定 🤣

**Comment by CodFrm** [comment]
@Basileusautokrator @414437542 在release重新下载试试,加了一个服务器在线检测

**Comment by cingneimaa** [comment]
![image](https://user-images.githubusercontent.com/39883136/41156752-cf23405e-6b55-11e8-9aee-fb541a90d61f.png)
作者大大看看能不能参照后台挂尔雅浏览器v1.9.2里面的“娜娜”答题插件，或者导入那个插件的题库？用了2科发现那个插件题库很全了，而超星慕课小工具除了军事理论以外还是搜不到答案，应该是上传样本太少了。

**Comment by Basileusautokrator** [comment]
现在1.42的扩展程序完美运行

**Comment by CodFrm** [comment]
@cingneimaa 他的题库我不知道，还是慢慢收集吧，后面准备加个手动导入的
