### ISSUE TITLE
关于部分外校（课程地址非超星官方网站）的插件加载问题

### ISSUE THREAD

**Issue by HoshinoTouko** [CodFrm/cxmooc-tools#25]
例如 WHU 的 MOOC 是在 WHU 自己的地址中的，需要手动把地址匹配放进去才能激活。以后是否有允许手动添加匹配地址的打算

![image](https://user-images.githubusercontent.com/13916411/41143715-e8c31a8a-6b2c-11e8-98e1-4b9b1a34bd56.png)

**Comment by CodFrm** [comment]
@HoshinoTouko 
=_=还有这样的操作....那么可以修改一下规则成一条,楼主试一下这样能不能匹配到?
```
"*://*/mycourse/studentstudy?*"
```
要是再有例外再说吧

![g9eo h0xcx17_x 3e9 m](https://user-images.githubusercontent.com/22783163/41149665-bfd4acc6-6b3e-11e8-8fb7-9d36a8f2037a.jpg)
![tim 20180608170914](https://user-images.githubusercontent.com/22783163/41149669-c333cf14-6b3e-11e8-9726-1730453f07c5.png)
