### ISSUE TITLE
全自动挂机开启下一个视频会自动跳过

### ISSUE THREAD

**Issue by psywalk** [CodFrm/cxmooc-tools#26]
**错误描述**
你所遇到的错误是怎么样的?全自动挂机开启下一个视频会自动跳过，进入答题环节，如果设置时间过短，会出现验证码提醒

**错误提示**
无

**出现时间**
开启全自动挂机，刷新，一个视频刷完、答完题，进入下一个视频，会跳过视频

**错误版本**
Chrome 版本 67.0.3396.79  软件 1.46

**Comment by CodFrm** [comment]
@psywalk 有没有截图?下一个视频是在同一个选项夹里面还是分开的?

**Comment by psywalk** [comment]
这个应该截不了，太快了，流程是：从一个已经完成的题目测试开始——》进入下一个任务的视频——》同一个页面播放界面刷新（中间可以看到更换播放器的字样）——》视频没有播放、直接跳到该任务的题目测试——》。。。不播放视频，只做题目，并且时间设置过短会出现输入验证码的选项

**Comment by CodFrm** [comment]
@psywalk 视频有没有任务点的标志?

**Comment by psywalk** [comment]
直接跳过，没有完成，相当于没有看过

**Comment by CodFrm** [comment]
@psywalk 好的,可能知道问题所在了,下一版本修复

**Comment by psywalk** [comment]
加油！

**Comment by CodFrm** [comment]
@psywalk 尝试一下只从列表页面进入,不要手动去操作更换页面,会不会出现上面情况

**Comment by psywalk** [comment]
会的（先打开全自动挂机，然后刷新，最后点击列表），学习目标过去之后，直接就跳到了测验环节

**Comment by psywalk** [comment]
时间设置长一些不会出现验证码，但是还会跳过视频

**Comment by CodFrm** [comment]
@psywalk 直接刷新就不要再操作了,这样试试,可能点击后又产生了一个计时器,冲突了

**Comment by hakettyan** [comment]
无法自动选择视频源，只能默认选择本校，但本校视频皆无法播放，故不能自动挂机。

**Comment by CodFrm** [comment]
@hakettyan ....我记得原来修复过一次 #19 

好像还有问题....重新弄了
