### ISSUE TITLE
本地题库 问题反馈&帮助

### ISSUE THREAD

**Issue by CodFrm** [CodFrm/cxmooc-tools#27]
> 如果不会写规则,可以将题库发上来,看到会帮忙的
> 题库用浏览器的localStorage储存,建议及时清理

![tim 20180621162244](https://user-images.githubusercontent.com/22783163/41706837-5c0d997e-756f-11e8-92e7-b4d120c99efd.png)
从设置题库导入

可以直接的将题库 **复制 粘贴** 到 **题库内容**

之后需要自己编写这个题库的匹配规则

使用**正则表达式**匹配 题目用 **{topic}** 代替 答案用 **{answer}** 代替

![tim 20180621162551](https://user-images.githubusercontent.com/22783163/41707035-c83206da-756f-11e8-9524-9b3e17a3943e.png)

点击确定会保存  下面的可以输入题目进行测试  成功之后就可以再做题的时候自动检索

![tim 20180621162705](https://user-images.githubusercontent.com/22783163/41707104-f4756bec-756f-11e8-8cdd-f11b100096aa.png)

**Comment by CodFrm** [comment]
@98line 分享的题库:[尔雅.最新军事理论课后答案%28同济版%29.docx](https://github.com/CodFrm/cxmooc-tools/files/2087147/28.29.docx)

规则:\d{1,6} {topic}我的答案：{answer}

![tim 20180621163615](https://user-images.githubusercontent.com/22783163/41707663-3f10d3ca-7571-11e8-98ef-01132aca8b05.png)

**Comment by lovetears** [comment]
[超星慕课《大学生职业生涯规划》答案大全.docx](https://github.com/CodFrm/cxmooc-tools/files/2152963/default.docx)
试了一下，不太会导入，求帮助

**Comment by god-xiang** [comment]
能帮我导入一下吗 谢谢``
[大学生健康教育.docx](https://github.com/CodFrm/cxmooc-tools/files/2169950/default.docx)

**Comment by CodFrm** [comment]
@god-xiang 
**\d{1,4}[\s+|【.*?】]{topic}（{answer}）**

![tim 20180706230614](https://user-images.githubusercontent.com/22783163/42386126-320a5c8a-8171-11e8-9e37-3715801e4ac9.png)

只测试了几个

**Comment by austinguish** [comment]
上海市大学生安全教育在线(学习与考试)
表达式为\d{1,1812},{topic},{answer}
[QA.txt](https://github.com/CodFrm/cxmooc-tools/files/2208656/QA.txt)

**Comment by youyouwutong** [comment]
[突发事件自救互救(尔雅)答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2384161/default.docx)
能帮下吗?谢谢

**Comment by youyouwutong** [comment]
> [突发事件自救互救(尔雅)答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2384161/default.docx)
> 能帮下吗?谢谢

\d{1,4}[\s+]{topic}我的答案：{answer}   这样的吗

**Comment by CodFrm** [comment]
> > [突发事件自救互救(尔雅)答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2384161/default.docx)
> > 能帮下吗?谢谢
> 
> \d{1,4}[\s+]{topic}我的答案：{answer} 这样的吗

对的，可以

**Comment by chaowangbka** [comment]
[数学史与数学教育2018尔雅满分答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2426896/2018.docx能帮我一下吗

**Comment by liuzhenghang** [comment]
弱弱问一下怎么只刷视频不答题，没有题库   随机答案太可怕了

**Comment by CodFrm** [comment]
> 弱弱问一下怎么只刷视频不答题，没有题库 随机答案太可怕了

@liuzhenghang 现在还不能只刷视频- -。。。

**Comment by chaowangbka** [comment]
> > [数学史与数学教育2018尔雅满分答案.docx]（[https://github.com/CodFrm/cxmooc-tools/files/2426896/2018.docx能帮我一下吗](https://github.com/CodFrm/cxmooc-tools/files/2426896/2018.docx%E8%83%BD%E5%B8%AE%E6%88%91%E4%B8%80%E4%B8%8B%E5%90%97)
> 
> @chaowangbka这种的好像不行 - -....不好匹配..

测试的时候可以匹配 但是答题时搜索不到是咋回事

**Comment by liuzhenghang** [comment]
最后提交题目的时候是模拟点击”提交答案“按钮么   在题库匮乏的时候如果不希望直接提交答案   而是暂时保存题目  这个可以实现么  我看了看源码并不是很清楚

**Comment by CodFrm** [comment]
@liuzhenghang 可以将答案保存在本地储存中

**Comment by zhangt2333** [comment]
![snipaste_2018-10-08_15-13-03](https://user-images.githubusercontent.com/35210901/46595868-f5e0da00-cb0c-11e8-82c9-21d658041cd5.png)
![snipaste_2018-10-08_15-13-18](https://user-images.githubusercontent.com/35210901/46595870-f5e0da00-cb0c-11e8-9cc3-7fbfe4b8caf5.png)
测试的时候可以匹配，具体搜索不到呀，大大

**Comment by CodFrm** [comment]
@zhangt2333 emmmm不清楚。。。。这个功能不是很完善

**Comment by DAZEmarisa** [comment]
@CodFrm 大佬，怎么样才能关闭自动提交答案的功能呢？

**Comment by CodFrm** [comment]
@DAZEmarisa 不能。。。。你可以把随机题目去掉，没有答案的会提示你

**Comment by DAZEmarisa** [comment]
> @DAZEmarisa 不能。。。。你可以把随机题目去掉，没有答案的会提示你

关闭随机答案后，我可以手动核对答案再手动提交吗？

**Comment by CodFrm** [comment]
> > @DAZEmarisa 不能。。。。你可以把随机题目去掉，没有答案的会提示你
> 
> 关闭随机答案后，我可以手动核对答案再手动提交吗？

呃。。。你可以不勾选挂机模式，手动点击搜索答案，没答案的会提示

**Comment by DAZEmarisa** [comment]
[戏曲鉴赏作业+期末考试答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2460971/%2B.docx)
贡献一波题库

**Comment by jackaroo0** [comment]
![25](https://user-images.githubusercontent.com/38932060/46900601-630eb980-ced7-11e8-8a33-0251efaae4a8.png)
这个怎么解决？

**Comment by jackaroo0** [comment]
问题网址沈阳理工大学慕课

**Comment by jackaroo0** [comment]
在搜索答案时出现的问题

**Comment by CodFrm** [comment]
@jackaroo0 服务器崩溃了，还在等工单回复😭😭😭😭

**Comment by jackaroo0** [comment]
> @jackaroo0 服务器崩溃了，还在等工单回复😭😭😭😭

好的，我还以为被修复了

**Comment by jackaroo0** [comment]
> @jackaroo0 服务器崩溃了，还在等工单回复😭😭😭😭

那修复大概要多久呢

**Comment by SBBTD** [comment]
> ![snipaste_2018-10-08_15-13-03](https://user-images.githubusercontent.com/35210901/46595868-f5e0da00-cb0c-11e8-82c9-21d658041cd5.png)
> ![snipaste_2018-10-08_15-13-18](https://user-images.githubusercontent.com/35210901/46595870-f5e0da00-cb0c-11e8-9cc3-7fbfe4b8caf5.png)
> 测试的时候可以匹配，具体搜索不到呀，大大

我也遇到了，貌似是因为前面那个【单选题】这三个字让他匹配不到

**Comment by luojunyuan** [comment]
> > ![snipaste_2018-10-08_15-13-03](https://user-images.githubusercontent.com/35210901/46595868-f5e0da00-cb0c-11e8-82c9-21d658041cd5.png)
> > ![snipaste_2018-10-08_15-13-18](https://user-images.githubusercontent.com/35210901/46595870-f5e0da00-cb0c-11e8-9cc3-7fbfe4b8caf5.png)
> > 测试的时候可以匹配，具体搜索不到呀，大大
> 
> 我也遇到了，貌似是因为前面那个【单选题】这三个字让他匹配不到

![屏幕截图(67).png](https://i.loli.net/2018/10/19/5bc8c3e8cb9dd.png)
我手动添加了 单选题 似乎还是不行检测不到，你们可否尝试一下

**Comment by wky809982944** [comment]
[什么是科学答案.docx](https://github.com/CodFrm/cxmooc-tools/files/2537174/default.docx)
按之前你匹配的规则不成功

**Comment by X237743972** [comment]
题库匹配好了，但是出现了一个问题从课后直接的原句在题库里面找不到
例如“【单选题】民主制度与专制制度的最大区别体现在()。”
在题库里面找不到
但是如果缺少字段匹配“民主制度”“民主制度与专制”等等残缺的关键字
就能找到答案，正则表达式我不是很懂，但是这个里面出现的问题我知道。
如果有大神能出一个 能模糊匹配关键字的示范 这个插件对于个人使用来说就完全足够了
![qq 20181115125626](https://user-images.githubusercontent.com/39017648/48531267-8feb2d80-e8d6-11e8-9a57-1257d70f24b0.png)
![qq 20181115125745](https://user-images.githubusercontent.com/39017648/48531268-91b4f100-e8d6-11e8-8f61-03c682a0daaa.png)

**Comment by CodFrm** [comment]
跑路了,跑路了,本地题库功能不打算维护了

![g4wd vno2 a ceml nw](https://user-images.githubusercontent.com/22783163/48533149-443c8200-e8de-11e8-918f-1cdab2a1ec26.jpg)
