### ISSUE TITLE
[BUG]题库无法访问，显示题库网络错误

### ISSUE THREAD

**Issue by benren175** [CodFrm/cxmooc-tools#272]
![QQ图片20211031180231](https://user-images.githubusercontent.com/93470305/139577884-e70b9c5f-75bb-4e47-862d-0fb3a33e250a.png)
用的火狐浏览器，只用的脚本没有用文档，出现这个问题是点到了更新2.5.7版本，更新完就显示题库网络异常，试过降级版本到2.5.5，可是还是不行。用别的电脑下载2.5.5脚本也出现了题库无法搜索的问题
Email：1415544537@qq.com

**Comment by hbchen121** [comment]
+1

**Comment by CodFrm** [comment]
经常被ddos，没办法
