### ISSUE TITLE
[BUG]超新星无法显示课程

### ISSUE THREAD

**Issue by achun701** [CodFrm/cxmooc-tools#273]
### 错误描述
> 你所遇到的错误是怎么样的?最好提供错误截图
![QQ图片20211103231148](https://user-images.githubusercontent.com/93666913/140090236-fdb565df-3398-4931-9084-01ae7472355a.png)

### 出现时间
第三次使用时

### 其它信息
> 1640714922@qq.com

**Comment by CodFrm** [comment]
emmm这是超星的问题吧。。。
