### ISSUE TITLE
可以考虑使用tampermonkey来load插件

### ISSUE THREAD

**Issue by RingoTC** [CodFrm/cxmooc-tools#28]
因为Chrome现在对非商店插件限制，动不动就让我卸载。只能安装一个双核浏览器来安装插件，其实可以考虑使用tampermonkey啊。这样就不用管Chrome的限制了。

**Comment by CodFrm** [comment]
chrome的限制确实是有些蛋疼....上次我申请了个交通银行的visa卡,想去验证google开发者的,结果和我说不支持,难受死了....(虽然就算验证过了,插件也不一定会过...)

油猴不了解,不过都已经这样了,就先用chrome插件的模式吧......以后看看能不能再弄一个油猴的版本...

**Comment by CodFrm** [comment]
已发布油猴版本啦~\(≧▽≦)/~啦啦啦

[https://greasyfork.org/zh-CN/scripts/376190-cxmooc-tools](https://greasyfork.org/zh-CN/scripts/376190-cxmooc-tools)
