### ISSUE TITLE
关于题库的导入

### ISSUE THREAD

**Issue by Nchinasss** [CodFrm/cxmooc-tools#284]
如何上传模板题库文件

**Comment by CodFrm** [comment]
直接发上来即可 https://github.com/CodFrm/cxmooc-tools/issues/100

**Comment by Nchinasss** [comment]
好的 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CodFrm/cxmooc-tools] 关于题库的导入 (Issue #284)






直接发上来即可#100

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人. 
***@***.***与&gt;
