### ISSUE TITLE
全自动挂机到下一个视频之后不会开始播放

### ISSUE THREAD

**Issue by cold-snap** [CodFrm/cxmooc-tools#29]
**错误描述**
全自动挂机时每当播放完一个视频，下一个视频 不会自动播放，而是一直在走进度条，怀疑这个问题与服务器设置有关系，我们只有选择了服务器2才会正常播放，感觉自动挂机停在了服务器1，然而当手动回到页面时会自动选择服务器2

**错误版本**
扩展 1.5.0
Chrome 67.0.3396.99 64位

**Comment by cold-snap** [comment]
补充，该页面后台时不会自动播放，目测此时处于黑屏状态没有加载视频，此问题无法截图，因为一旦回到前台就会加载视频开始播放，此问题带来的后果是emmmm自动下一集形同虚设…………
希望大大能排查一下

**Comment by CodFrm** [comment]
@cold-snap 

好像是的...可能是浏览器在后台的时候代码无法运行吧....然后就无法进入下一集,只能前台播放.... 🤣
