### ISSUE TITLE
搜索答案出错

### ISSUE THREAD

**Issue by Dreace** [CodFrm/cxmooc-tools#30]
**错误描述**
如图
![pn w zc u 02w mftevk](https://user-images.githubusercontent.com/13167128/44131685-47aac176-a087-11e8-951c-9fb0070b9c01.png)

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
答题界面点击搜索答案

**错误版本**
浏览器：Google Chrome 67.0.3396.87（正式版本） （64 位）
插件：1.5

**Comment by Dreace** [comment]
可是我已经导入本地题库，测试没有问题
看了半天代码没找到问题，只能请求帮助了

**Comment by CodFrm** [comment]
@Dreace 本地题库功能还有点问题,能上传一下,让我看看吗?还有题目

**Comment by CodFrm** [comment]
不行的话,建议还是手动的填一下=w=...

**Comment by Dreace** [comment]
好的呢 我也再研究研究
