### ISSUE TITLE
无法添加到chrome

### ISSUE THREAD

**Issue by wannaAC** [CodFrm/cxmooc-tools#31]
**错误描述**
你所遇到的错误是怎么样的?

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by wannaAC** [comment]
crx文件添加到chrome会被自动停用，且无法启用。用开发者模式添加已解压的文件夹提示文件损坏。求破

**Comment by CodFrm** [comment]
@wannaAC 应该是你的导入方式不正确导致的

**Comment by haitaochen** [comment]
我是直接把crx 拖进去，然后列表里面有但是那个启用插件的开关不能开是禁用状态。
后来我把那个压缩包解压按文档里的方式解压加载扩展程序会弹窗显示：
清单文件缺失或不可读取无法加载清单。

**Comment by CodFrm** [comment]
@haitaochen chrome浏览器不能直接拖，qq浏览器可以

挂机是安全的，只是防止视频被暂停停止播放而已，秒过会有被检测的风险

**Comment by haitaochen** [comment]
@CodFrm 非常感谢，博主很棒！

**Comment by CodFrm** [comment]
@wannaAC 不是的，chrome系列的都行，只是你安装姿势不正确
