### ISSUE TITLE
无法自动切换播放网络 导致无法自动开始下一个视频

### ISSUE THREAD

**Issue by 919482623** [CodFrm/cxmooc-tools#33]
**错误描述**
你所遇到的错误是怎么样的?

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by 919482623** [comment]
播放网络有本校，公网1和2，我得连接公网才能播放，但是下个视频开始时默认是本校。请问有没有哪里可以设置？谢谢大神

**Comment by 919482623** [comment]
我用得是chrome

**Comment by 919482623** [comment]
拓展是最新版1.51

**Comment by CodFrm** [comment]
因为播放器更新了。。。。这个问题还没解决

**Comment by 919482623** [comment]
> @919482623 因为播放器更新了。。。。这个问题还没解决

owo，那只能表示期待了hhhh

**Comment by dovela** [comment]
同样碰到这个问题...

**Comment by CodFrm** [comment]
cdn记录切换以增加
