### ISSUE TITLE
不会自动切换到公网ip，视频播放完又从头开始播放，不知道是不是因为看过的原因。自动答题的文件不知道怎么使用

### ISSUE THREAD

**Issue by poorblack** [CodFrm/cxmooc-tools#34]
**错误描述**
你所遇到的错误是怎么样的?

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by poorblack** [comment]
播放源有三个：公网 本校1 本校2，没有连接校园网的时候只能用公网播放，但是视频不会自己跳转播放源，需要自己手动。还有那个答题的能不能集成到软件里

**Comment by CodFrm** [comment]
@poorblack 播放源切换这个还没有修复

**Comment by CodFrm** [comment]
视频播放完又从头开始播放的bug修复了

播放源记录已完成
