### ISSUE TITLE
挂完视频后练习题也答了，但是不会自己往下一个视频跳

### ISSUE THREAD

**Issue by Fnckerpoi** [CodFrm/cxmooc-tools#35]
**错误描述**
你所遇到的错误是怎么样的?
挂完视频后练习题也答了，但是不会自己往下一个视频跳
**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?
手动点下一个视频
**错误版本**
你的浏览器版本和扩展的版本
谷歌69，最新的插件版本
我看作者介绍不是已经可以支持自动跳下一个视频吗

**Comment by CodFrm** [comment]
@Fnckerpoi 有截图吗？

**Comment by DDGirt** [comment]
我也是，无法自动换到下个视频，播完就停止了

**Comment by CodFrm** [comment]
> 我也是，无法自动换到下个视频，播完就停止了

能不能看看截图?选项那里有没有勾上?

**Comment by DDGirt** [comment]
> > 我也是，无法自动换到下个视频，播完就停止了
> 
> 能不能看看截图?选项那里有没有勾上?

![qq 20180930211950](https://user-images.githubusercontent.com/34884790/46257992-1221bd00-c4f6-11e8-9c56-5198a7215376.png)
有，我还把时间间隔改为2和0，都没什么效果

**Comment by CodFrm** [comment]
@DDGirt 设置为0.1试试

**Comment by moshiyeap** [comment]
在最新的Chrome中无法开启本插件。
提示 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by CodFrm** [comment]
间隔时间单位是分，不知道你们的是什么情况，可以f12提供console给我看看么？

**Comment by Fnckerpoi** [comment]
emmmmmmmm，原来单位是分阿.......那我设置短一些吧。但是我挂了一个通宵也没刷几个视频

**Comment by CodFrm** [comment]
@Fnckerpoi 如果还不行，f12吧console里的内容贴上来看看

**Comment by Fnckerpoi** [comment]
好的，我可能要后天才可以，我出去旅游了，手上的电脑是linux不知道为什么看不了网课，要到时候用win的电脑才行

**Comment by Fnckerpoi** [comment]
我也不知道为什么用linux看不了网课，不知道哦是不是没有它要求的播放器还是真的是网络问题

**Comment by CodFrm** [comment]
@Fnckerpoi linux的话。。。没问题啊，我都试过

**Comment by DDGirt** [comment]
![qq 20181004143418](https://user-images.githubusercontent.com/34884790/46456705-58bb3400-c7e2-11e8-8f4b-6129d970a314.png)
![qq 20181004143445](https://user-images.githubusercontent.com/34884790/46456714-607ad880-c7e2-11e8-9d9a-1f4a65e35f3a.png)
还是不行，大佬你自己有试过吗，不能自动播下一个视频，我是UC浏览器

**Comment by CodFrm** [comment]
UC 没有测试过...UCwindows的吗?有没有试过chrome或者qq浏览器之类的能不能?

**Comment by CodFrm** [comment]
@DDGirt 对了。。。你下一个视频是怎么样的?题目后面还是?

**Comment by DDGirt** [comment]
> @DDGirt 对了。。。你下一个视频是怎么样的?题目后面还是?

![qq 20181005113218](https://user-images.githubusercontent.com/34884790/46514683-eace4580-c891-11e8-8a32-e65634865271.png)
不行，换chrome浏览器也这样

**Comment by DDGirt** [comment]
![qq 20181005113518](https://user-images.githubusercontent.com/34884790/46514739-41d41a80-c892-11e8-8dda-20a353ba9f01.png)

**Comment by CodFrm** [comment]
@DDGirt 好吧。。报错了，不过暂时不知道怎么解决

**Comment by CodFrm** [comment]
已修复
