### ISSUE TITLE
在Chrome 69.0.3497中无法开启插件

### ISSUE THREAD

**Issue by moshiyeap** [CodFrm/cxmooc-tools#36]
提示：该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。
你的浏览器版本和扩展的版本
版本 69.0.3497.100（正式版本） （64 位）
1.5.1

**Comment by CodFrm** [comment]
开启开发者模式安装

**Comment by moshiyeap** [comment]
> 开启开发者模式安装

已经开启了，查了Chrome的FAQ好像是没有在商店上架的插件都不能启用

**Comment by CodFrm** [comment]
可以的，看教程说明

**Comment by moshiyeap** [comment]
> 可以的，看教程说明 ，需要解压成文件

谢谢您 解决了 ！
