### ISSUE TITLE
插件无法答题了，我和我舍友的都不行了

### ISSUE THREAD

**Issue by LittleControl** [CodFrm/cxmooc-tools#39]
**错误描述**
你所遇到的错误是怎么样的?
点击搜索答案后无反应，然后提示遇到遇到未知错误

**错误提示**
有没有错误的提示,没有不填写
提示遇到未知错误

**出现时间**
你是怎么操作出现的这个错误?
点击搜索答案之后没有反应
**错误版本**
你的浏览器版本和扩展的版本
浏览器是谷歌浏览器69.0.3497.100（正式版本） （64 位）
扩展版本是最新的那个crx

**Comment by CodFrm** [comment]
嗯。。。。因为操作失误，服务器蹦了。。。。。还在等工单，看看能不能恢复😭😭

**Comment by LittleControl** [comment]
> 嗯。。。。不知道怎么服务器蹦了。。。。。还在等工单，看看能不能恢复😭😭

嗯嗯，没事没事，不急，您先忙，我们这都不着急的，有什么需要的随叫随到（在我的能力范围内🤭）

**Comment by wxevu** [comment]
不着急

**Comment by CodFrm** [comment]
恢复了_(´ཀ`」 ∠)_
