### ISSUE TITLE
关于cxmooc提醒

### ISSUE THREAD

**Issue by zhangt2333** [CodFrm/cxmooc-tools#4]
不建议秒看，秒看只要查一定能查到啊....

我刚开始上cx课时候也是想到破解，F12工具抓包后发现视频播放时候每10s就往服务器发一个包，然后又事先听闻有学长刷课被导员叫去批评了，于是没往秒看的方向去做。

我是做的后台自动挂机和弹题提醒(手动答题滑稽)，用电脑的时候就挂一下，一周挂完了。

(最近cx登录界面下还有警告  汗...)

**Comment by CodFrm** [comment]
这个确实是很容易被查到QWQ,不过并不一定要用啊,下一个版本就将颜色更改为红色警示吧,功能还是留着....
不同的学校对这个监管程度不同,可能你都秒了也没问题

楼主倒是给了我一点灵感,不知道能不能模拟发包和答题,时间还是那么过着,只是对挂机模式一个优化,模拟看完一个视频之后再跳入下一个视频,这样就不需要手动的去点挂机了
现在的方式是获取网页的flash对象,来操作视频切换后台播放,有很多小毛病

**Comment by CodFrm** [comment]
正准备尝试使用封包的方式实现挂机,具体效果还不知道会怎么样

**Comment by zhangt2333** [comment]
当初想到模拟发包没敢做（瑟瑟发抖，看git主js写各种插件方便，拿py写爬虫拿课程列表弹题答案还要想方设法拿cookie的我泪流满面，话说我下学期的尔雅课来拿试试（如果不被河蟹的话
