### ISSUE TITLE
能否添加自动播放下一集的功能

### ISSUE THREAD

**Issue by 15klli** [CodFrm/cxmooc-tools#40]
**错误描述**
你所遇到的错误是怎么样的?

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by CodFrm** [comment]
自动播放下一集是可以的啊？能否提供一下截图

**Comment by 15klli** [comment]
> 自动播放下一集是可以的啊？能否提供一下截图

有误会。我所指的自动播放下一集是指  **看完1.1视频后自动播放1.2视频，不需要做题目**。ps：因为题目我想后面有时间自己做

**Comment by CodFrm** [comment]
e71980848fdb18d08c6a498ac8fb934df04d3018
