### ISSUE TITLE
希望加入自动静音功能

### ISSUE THREAD

**Issue by Cookiekira** [CodFrm/cxmooc-tools#41]
**错误描述**
你所遇到的错误是怎么样的?

**错误提示**
有没有错误的提示,没有不填写

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by CodFrm** [comment]
好的，下一个版本更新

**Comment by CodFrm** [comment]
be734432fe569d17e2f25410844eb4b10dc9feaf
