### ISSUE TITLE
README.md 文件中“重命名为rar”不妥

### ISSUE THREAD

**Issue by SadPencil** [CodFrm/cxmooc-tools#42]
`下载发布的版本cxmooc-tools.crx文件，修改后缀为.rar，并将其解压。`
应为 `下载发布的版本cxmooc-tools.crx文件，修改后缀为.zip，并将其解压。`

虽然修改为.rar文件也可被大多数压缩软件识别，但此文件实际上(去掉crx的文件头后)为ZIP格式，不应使用.rar扩展名。
————
当然，常见压缩软件中只有WinRAR能忽略crx的特殊文件头而正确地解压文件。

**Comment by CodFrm** [comment]
已修改，感谢指出
