### ISSUE TITLE
建议秒过视频加一个二次确认

### ISSUE THREAD

**Issue by VonXXGhost** [CodFrm/cxmooc-tools#43]
或者提供不显示此按键的选项，不然很可能误操作点到一下就触发了。毕竟这是一个危险度很高的功能

**Comment by VonXXGhost** [comment]
> 我觉得...这两个按钮的区分度还是挺高的吧(托腮)

但是两个按钮靠得很近，有可能会因为网页加载延迟/手抖等原因不小心点到。（之所以提这个issue就是因为才被这样坑了一遍……

**Comment by CodFrm** [comment]
@VonXXGhost :lol:

**Comment by IKonwYourDepth** [comment]
之前看好像是说过题秒过也会被检测，而且好像全自动挂机的间隔时间没什么用啊，还是我哪里用的不对？

**Comment by CodFrm** [comment]
@IKonwYourDepth 间隔单位是分钟，不知道你是怎样的

**Comment by IKonwYourDepth** [comment]
> @IKonwYourDepth间隔单位是分钟，不知道你是怎样的

所以说间隔5分钟的意思是章节测试填上答案5分钟后提交么？

**Comment by CodFrm** [comment]
@IKonwYourDepth 是的

**Comment by IKonwYourDepth** [comment]
> @IKonwYourDepth 是的

啊，真的感谢大佬的工具，真的帮了我们不少忙，感谢感谢

**Comment by CodFrm** [comment]
04b4ab5614fb3a35e3a7b029a0bc379ecffa41ca

增加
