### ISSUE TITLE
您还有未做完的多选题，确认提交吗？

### ISSUE THREAD

**Issue by RuioWolf** [CodFrm/cxmooc-tools#45]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图
![image](https://user-images.githubusercontent.com/15277799/48313460-e830df80-e5f7-11e8-830b-5c43a1b95154.png)

**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)
![image](https://user-images.githubusercontent.com/15277799/48313478-2201e600-e5f8-11e8-98a7-bd13fdc3cd6d.png)

**出现时间**
有多选题的时候

**错误版本**
你的浏览器版本和扩展的版本
![image](https://user-images.githubusercontent.com/15277799/48313475-17dfe780-e5f8-11e8-990c-0e6e6afa26fc.png)

**Comment by CodFrm** [comment]
@RuioWolf 
楼主的配置是没有开启随机答案?

可能是没有搜索到答案,然后就自动提交了,提示了这个信息框

**Comment by RuioWolf** [comment]
> @RuioWolf
> 楼主的配置是没有开启随机答案?
> 
> 可能是没有搜索到答案,然后就自动提交了,提示了这个信息框

的确没有打开随机答案 但是即使没有打开（单选和判断）题目也是自动提交的 只有有多选题的情况下才会卡住不动

**Comment by CodFrm** [comment]
@RuioWolf 手动的情况下,多选题有没有填入答案?

**Comment by RuioWolf** [comment]
> @RuioWolf 手动的情况下,多选题有没有填入答案?

填了 但是没有办法提交

**Comment by CodFrm** [comment]
@RuioWolf 好吧...暂时了解了,有时间会看的,谢谢反馈

**Comment by pinkpeachabc** [comment]
这个bug好像是题库的问题  这个bug只有特定的几章里面才会出现 我看不同的课程测试这个问题 感觉是题库的问题  点了随机答案也还是出现
