### ISSUE TITLE
似乎遇到视频中间的题目不会答

### ISSUE THREAD

**Issue by sss465785** [CodFrm/cxmooc-tools#47]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by CodFrm** [comment]
嗯，还没用修复

**Comment by CodFrm** [comment]
@RuioWolf 楼上的方法可以防止显示题目,这个题目答不答好像都问题不大,不过有时间我还是去更新一下视频答题的功能

**Comment by CodFrm** [comment]
以重构
