### ISSUE TITLE
全自动挂机有时侯自动答题会失效

### ISSUE THREAD

**Issue by 751235336** [CodFrm/cxmooc-tools#50]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by 751235336** [comment]
![1_00](https://user-images.githubusercontent.com/45375482/49052459-eb96ae80-f226-11e8-8011-e757d91fb675.jpg)
![2_00](https://user-images.githubusercontent.com/45375482/49052462-f18c8f80-f226-11e8-9868-5ba0a9a02a99.png)

**Comment by Arthur-Mi** [comment]
搜索答案时显示错误
![tim 20181128220312](https://user-images.githubusercontent.com/31003353/49157066-e38b5b80-f359-11e8-9e46-0f490f8069cd.png)
![tim 20181128220348](https://user-images.githubusercontent.com/31003353/49157067-e38b5b80-f359-11e8-8a82-409d0b8e0361.png)

**Comment by minioo99** [comment]
我也遇到不能自动跳到下一个视频（已设置忽略题目），会卡在答题的那个页面

**Comment by CodFrm** [comment]
以重构
