### ISSUE TITLE
判断题随机生成答案无效

### ISSUE THREAD

**Issue by ithg** [CodFrm/cxmooc-tools#51]
**错误描述**
![image](https://user-images.githubusercontent.com/25723505/49147147-d3b24e00-f33e-11e8-8c92-6935b46a1888.png)

**错误版本**
chrome 70.0.3538

**Comment by CodFrm** [comment]
好的收到了，我有时间会去看看，感谢反馈

**Comment by Arthur-Mi** [comment]
现在搜索答案显示未知错误

**Comment by CodFrm** [comment]
> 现在搜索答案显示未知错误

现在呢？好了吗？

**Comment by Arthur-Mi** [comment]
> > 现在搜索答案显示未知错误
> 
> 现在呢？好了吗？

ok，可以了，感谢

**Comment by CodFrm** [comment]
以重构
