### ISSUE TITLE
不能跳过答题到下一个视频

### ISSUE THREAD

**Issue by minioo99** [CodFrm/cxmooc-tools#52]
**错误描述**
会卡在答题的那个页面
**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)

**出现时间**
你是怎么操作出现的这个错误?
2018-11-29 13:19
**错误版本**
你的浏览器版本和扩展的版本
谷歌浏览器

**Comment by minioo99** [comment]
![tim 20181129134606](https://user-images.githubusercontent.com/42733503/49201759-22aec080-f3dd-11e8-9ff4-500abf2521f8.png)

**Comment by CodFrm** [comment]
以重构
