### ISSUE TITLE
按钮被挡住

### ISSUE THREAD

**Issue by ithg** [CodFrm/cxmooc-tools#53]
**错误描述**
![image](https://user-images.githubusercontent.com/25723505/49556080-36a67500-f93d-11e8-957b-554c27b2d44b.png)

**出现时间**
或许是视频顶部有字导致了bug出现？

**错误版本**
chrome、插件皆为最新

**Comment by ithg** [comment]
F5了一下 又不出现了 :sweat_smile:

**Comment by CodFrm** [comment]
> F5了一下 又不出现了

:sweat_smile::sweat_smile:这个就有点奇怪了

**Comment by CodFrm** [comment]
自己这边复现了，具体问题还未知，有时间看看，记录一下

**Comment by CodFrm** [comment]
fix
752132cc6e06c35fd339dcd0ea37e732901198c3
