### ISSUE TITLE
建议作者在video这里搞一下加速 这个不会被检测到 节约时间

### ISSUE THREAD

**Issue by Sato-Falisa** [CodFrm/cxmooc-tools#54]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by CodFrm** [comment]
这个可以考虑，后面有时间试一试

**Comment by CodFrm** [comment]
#04b4ab5614fb3a35e3a7b029a0bc379ecffa41ca

增加
