### ISSUE TITLE
刷题时出现未知错误

### ISSUE THREAD

**Issue by LUBIXUAN** [CodFrm/cxmooc-tools#55]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示**
有没有错误的提示,没有不填写(在浏览器中f12打开开发者工具，console的错误提示)

**出现时间**
你是怎么操作出现的这个错误?

**错误版本**
你的浏览器版本和扩展的版本

**Comment by LUBIXUAN** [comment]
刷题无法进行

**Comment by vb584317716** [comment]
![qq 20181222114945](https://user-images.githubusercontent.com/45680416/50370341-bbe98500-05df-11e9-8566-b4df9bf56620.png)

**Comment by CodFrm** [comment]
没注意到期时间。。。。服务器给停了。。。已修复
