### ISSUE TITLE
刷课

### ISSUE THREAD

**Issue by vb584317716** [CodFrm/cxmooc-tools#56]
能不能加个跳过填空题的，不然要一直点，每天还要上课，拜托拜托

**Comment by CodFrm** [comment]
一直点？什么意思？因为填空题不会自动填写的原因么？

**Comment by vb584317716** [comment]
是的，有填空题不用答不出来，希望能跳过

**Comment by CodFrm** [comment]
是本来就可以不用填么？看看题目类型

**Comment by vb584317716** [comment]
要填，但是直接跳过就行，要填空的课被我点完了，还有要加附件的

**Comment by CodFrm** [comment]
就是直接不考虑题目有没有做完，都直接提交么，这个可以加入一下，我周末有时间再看看吧 :rofl:

**Comment by KeyToon9** [comment]
挂了一天发现只有视频看了，章节检测都没有做，是哪里设置有问题吗？

**Comment by CodFrm** [comment]
> 挂了一天发现只有视频看了，章节检测都没有做，是哪里设置有问题吗？

你是不是勾选了忽略题目?

**Comment by KeyToon9** [comment]
> > 挂了一天发现只有视频看了，章节检测都没有做，是哪里设置有问题吗？
> > @KeyToon9
> > 你是不是勾选了忽略题目?

浏览器插件换成了油猴脚本，忘记设置了

**Comment by yb2019w** [comment]
为什么切换下一节要五分钟后才自动切换？

**Comment by CodFrm** [comment]
已有答案不全,自动忽略跳过
