### ISSUE TITLE
chrome 快进限制

### ISSUE THREAD

**Issue by BlackHole1** [CodFrm/cxmooc-tools#57]
**错误描述**
当调整播放速度为20时

**错误提示**
Uncaught DOMException: Failed to set the 'playbackRate' property on 'HTMLMediaElement': The provided playback rate (20) is not in the supported playback range.

经过查询，发现chrome只允许最大16.推荐在插件里进行说明，详情可见:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/media/html_media_element.cc?l=170&gsn=kMinRate

**Comment by CodFrm** [comment]
这个确实没注意，下一个版本标识一下

**Comment by CodFrm** [comment]
a8688d5775c68c5d44a1e92c8ca13550099bcf2a
