### ISSUE TITLE
重构计划v2.0.0

### ISSUE THREAD

**Issue by CodFrm** [CodFrm/cxmooc-tools#59]
> 由于刚开始并没有太过在意,后面增加新功能也是填鸭子式的,造成现在代码混乱,修复bug也难度上升.虽然现在时间不多,但是看见有很多小伙伴陆续加入群反馈~~和玩耍~~还是很开心的,于是准备重构插件,继续开始慢慢维护.

## TODO
> 先将重要的几项功能重构,后续再增加新的平台,下面列出优先级功能最高的功能,有其他计划的话再陆续增加,对于考试答题因为不好调试,先观望.
> 
> 完成部分功能和修复bug,会更新release页面的2.0.0-beta,最后再正式发布2.0.0.希望能够得到一些反馈.

* [x] 视频挂机
* [x] 视频秒过
* [x] 题库搜题
* [x] 题库上传
* [x] 自动挂机
* [x] 随机答案
* [x] 自动阅读
* [x] 全自动功能优化
* [x] 新的设置页面
* [x] 火狐浏览器的版本
...

**Comment by yanyongyu** [comment]
# TODO

- [ ] 阅读题

考虑一下咋样

**Comment by CodFrm** [comment]
@yanyongyu 没有遇到过,提供下账号呗

**Comment by CodFrm** [comment]
完成
