### ISSUE TITLE
超星上自动挂机失效

### ISSUE THREAD

**Issue by 562836456** [CodFrm/cxmooc-tools#6]
rt。

**Comment by CodFrm** [comment]
开始挂机现在是操作flash对象,切换后台暂停继续播放,有一些小毛病

楼主可以试试先将视频播放,然后再点击开始挂机,看看这样切换能不能继续播放

**Comment by CodFrm** [comment]
正准备尝试使用封包的方式实现挂机,具体效果还不知道会怎么样

**Comment by CodFrm** [comment]
#7

**Comment by Yousanflics** [comment]
老哥还是不行哇 超星现在不能自动挂机 唉 难受了

**Comment by CodFrm** [comment]
@Yousanflics 可能有点难点出来....在想办法优化,试试我上面说的呗

先播放视频,鼠标移出去会暂停,然后点开始挂机,然后再点开始播放,鼠标移动出去暂停,然后等一两秒看看会不会继续播放

**Comment by Yousanflics** [comment]
还是。。。上不去 而且这个题目 也基本是百度出来 唉 兄弟 加油优化吧 等你消息

**Comment by CodFrm** [comment]
@Yousanflics 准备用另外一种方法实现真半自动挂机了,但是不知道有没有风险,如果可以全自动挂机应该就差不多了

题目的话我也没去收集过,确实是硬伤,只能靠第一个人做完然后提交,之后的人就可以搜索到了

**Comment by Yousanflics** [comment]
问题是感觉应该没有这样的volunteer 老哥我觉得你这个项目先做起来 先别公开 不然很容易被 那边的后台人员给封了

**Comment by CodFrm** [comment]
@Yousanflics 这个应该问题不大,有办法封就有办法解,除非他们不干了233

**Comment by Yousanflics** [comment]
有点牛批 兄弟
