### ISSUE TITLE
关于不良记录

### ISSUE THREAD

**Issue by Chihiromis** [CodFrm/cxmooc-tools#65]
Chrome73 最新版
请问播放速度不是1倍速 是不是就很容易被监测到 我看手机上都可以调到2倍速 所以在2倍速内播放是不是比较安全

**Comment by CodFrm** [comment]
按道理来说是的,不过建议还是不要调倍速

**Comment by Chihiromis** [comment]
> 按道理来说是的，不过建议还是不要调倍速

谢谢回复 我上网搜了搜 发现有人手机二倍速都会被警告。。我还是一倍速吧

**Comment by Coquettishchild** [comment]
智慧树秒过会有不良记录吗

**Comment by CodFrm** [comment]
> 智慧树秒过会有不良记录吗

@Coquettishchild 不清楚智慧树有没有不良这么一说,但凡是作弊行为都会有风险
