### ISSUE TITLE
建议可以锁定某一个源来播放

### ISSUE THREAD

**Issue by kermonds** [CodFrm/cxmooc-tools#71]
**错误描述**
本校源不可用时就会无限等待，切换为公网1时正常，建议添加选定源的操作

![360截图-22727312](https://user-images.githubusercontent.com/49517675/55947789-c2306980-5c81-11e9-9859-086342f149a6.jpg)
![360截图-22744968](https://user-images.githubusercontent.com/49517675/55947808-cbb9d180-5c81-11e9-87d6-113d4c45b1a7.jpg)
![360截图-22774500](https://user-images.githubusercontent.com/49517675/55947818-cf4d5880-5c81-11e9-936d-52e7b81729cd.jpg)

**出现时间**
2019/4/11 

**错误版本**
360浏览器 chrome 63

**Comment by CodFrm** [comment]
你切换一次之后就会自动锁定那个源，难道没有吗？

**Comment by kermonds** [comment]
目前是一直锁定本校源

**Comment by CodFrm** [comment]
@kermonds 好的，晚些我测试一下

**Comment by kermonds** [comment]
> 你切换一次之后就会自动锁定那个源，难道没有吗？

目前是一直锁定本校的源 ，估计是超星的bug

**Comment by kermonds** [comment]
> @kermonds 好的，晚些我测试一下

谢谢，review了好几次网页代码，插件应该没有问题，估计是超星的工程师的锅😭

**Comment by AngleQingYuang** [comment]
用油猴一次同时挂机多个视频没事吧？

**Comment by CodFrm** [comment]
@kermonds 可以的话可以提供一下账号测试吗?

邮箱:love@xloli.top

**Comment by CodFrm** [comment]
已增加失败时手动切换记录cdn edc64a6e52168a8f80a9ce1fb2ca7041a18b0c01
