### ISSUE TITLE
公网1

### ISSUE THREAD

**Issue by Emiliails** [CodFrm/cxmooc-tools#77]
**错误描述**
你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
手动切换一次...然后就会记录你所选择的视频源.....

**Comment by Emiliails** [comment]
> @Emiliails 手动切换一次...然后就会记录你所选择的视频源....
的确是这样。 是我最小化浏览器窗口导致不能记录我选择的视频源。。。。
