### ISSUE TITLE
chrome视频播放完毕，且答案回答完毕，不能进行跳转

### ISSUE THREAD

**Issue by BierOne** [CodFrm/cxmooc-tools#78]
**错误描述**
![image](https://user-images.githubusercontent.com/26024460/57971287-a033b080-79be-11e9-9a16-b902c1842d07.png)
停留在此页面
**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)
![image](https://user-images.githubusercontent.com/26024460/57971300-c0fc0600-79be-11e9-83c3-b7dfdbe56bc5.png)

**出现时间**
![image](https://user-images.githubusercontent.com/26024460/57971314-e557e280-79be-11e9-8df4-ad5cd9467df8.png)
config如上图

**错误版本**
油猴,Chrome,version：2.101

**Comment by BierOne** [comment]
最近需要急用，希望authors看到能尽快解决，十分感谢！

**Comment by CodFrm** [comment]
@BierOne  可以试一下插件版本,油猴维护精力不多

这个我也会去看一下的

**Comment by CodFrm** [comment]
@BierOne  现在还有出现吗?

**Comment by CodFrm** [comment]
@BierOne 能不能给出你的任务点是怎么样的

**Comment by BierOne** [comment]
我用你们打包好的浏览器成功运行啦

**Comment by BierOne** [comment]
现在还没测试，当时用chrome的插件版本也不行。很感谢authors的解答

**Comment by CodFrm** [comment]
> 现在还没测试，当时用chrome的插件版本也不行。很感谢authors的解答

@BierOne 呃...所以是有成功吗?
