### ISSUE TITLE
如何讲视频直接跳过切记录为完成时间？

### ISSUE THREAD

**Issue by wankaiss** [CodFrm/cxmooc-tools#79]
你好：
  我checked智慧树的源代码js，我发现无论我是将播放速率调整为十倍还是将videojs的currentTime（这个是为了直接跳过播放时间）设置为duration（这个是视频总时长）都不可以吧当前视频mark为complete。请问author你是如何将这个视频标记为完成的呢？再者，我现在只是简单的跳过所有答题的页面通过jquery remove all node（通过一小段javascript in console tab）。如果我直接跳过视频打点的问答可否有任何问题呢？并且我怎样多开浏览器而不被kindly remind of mutil-page?

谢谢：
Newbie

**Comment by CodFrm** [comment]
@wankaiss  智慧树是按照右方的进度条来计算跳转的,达到100%判断为完成.
你通过jq移除节点那是你前端行为,后端不会记录.
浏览器多开你可以拦截掉它的检测地址,比如adblock工具.

**Comment by wankaiss** [comment]
是的， 只是我不知道如何将右方的进度条提前，所以我去参见了一下videojs的源码，但是还是没有找到合适的方法（譬如之前的set currentTime）。 不知作者有任何的方法直接提前呢？我没有找到相关的生成在智慧树和videojs的js代码中。

**Comment by CodFrm** [comment]
将右方进度条提前（加速吧）我没有看过，可能有点难实现，可以参考我的秒过，秒过原理是发送http包直接达到100%的进度
