### ISSUE TITLE
“欧洲文明概论”无法自动答题

### ISSUE THREAD

**Issue by kuangshao11** [CodFrm/cxmooc-tools#8]
或许是题库未收录？我看“正解网”上的答案还挺全的，希望开发者可以参考一下，把他们的题库扒过来之类的....附一个例子   https://www.zhengjie.com/question/289C8636

**Comment by CodFrm** [comment]
@kuangshao11 应该是题库未收录,现在是要有人做过,题库才会进行收录，没有做过的就搜索不到

才知道有一个这个网站能搜答案,可以考虑吧他们的答案爬下来,扩充题库

**Comment by CodFrm** [comment]
准备弄一个未搜索到答案的,显示一个跳转到这个网站的搜索链接
