### ISSUE TITLE
火狐看完超星后不自动跳转下个小节，还有题库出错了，不知道啥情况

### ISSUE THREAD

**Issue by BG8CFB** [CodFrm/cxmooc-tools#80]
**错误描述**
火狐看完超星后不自动跳转下个小节，还有题库出错了，不知道啥情况
![图片](https://user-images.githubusercontent.com/50827102/58012783-d5a7dd80-7b27-11e9-822a-5fbc645a935b.png)
本身网络没问题，完全正常。
**错误提示和日志内容**
TypeError: $(...).parents(...)[0] is undefined[详细了解] mooc.js:1:11324
    h moz-extension://3d25bf80-e657-4e6e-8b7a-4a05ef1ddfde/src/mooc.js:1
    p moz-extension://3d25bf80-e657-4e6e-8b7a-4a05ef1ddfde/src/mooc.js:1
    n moz-extension://3d25bf80-e657-4e6e-8b7a-4a05ef1ddfde/src/mooc.js:1

**出现时间**
不自动跳转下个小节是浏览器多开，题库是有一段时间了

**错误版本**
火狐

**Comment by CodFrm** [comment]
f12 console中有什么错误信息吗？然后就是试一试访问https://cx.icodef.com 或者 https://blog.icodef.com:8081 看看有没有拦截，如果有允许访问

**Comment by BG8CFB** [comment]
首先在这里感谢您开发的小工具，我希望向你提一下我认为可以改进的地方，让网络题库记录错误答案并排除该选项，还有一个小问题就是间隔最好可以设置为一段时间随机提交，比如1-2分钟之间提交，因为我有个同学被不良记录了，没有秒过视频，倍数和拖动进度条，问客服后反馈为140多个小节你全部间隔为2分钟，所以说是刷课。对了题库特别不完善，我有个同学考试自动答题为好多都没有。第一次直接没及格。最后还是特别感谢你，让我有这样方便的小工具。
题库错误不是我一个人出现了这样的问题，我们整个学校还有其他一些学校都是，你让我访问的网址并没有被拦截。
还有我发的就是控制台里面的错误，其他的全是黄色的警告
访问结果：
欢迎使用超星慕课刷课插件
这个服务器将会记录你正确的答题答案,并不会记录你的任何账号信息
并且接口没有任何权限,全由插件提交上传,还请大家不要故意上传错误的答案 (๑• . •๑)

**Comment by BG8CFB** [comment]
> 
> 
> F12 console中有什么错误信息吗然后就是试一试访问 ？[https://cx.icodef.com(https://cx.icodef.com)](https://cx.icodef.com)或者[https://blog.icodef.com:8081(https://blog.icodef.com:8081)](https://blog.icodef.com:8081)看看有没有拦截如果有允许访问 ，

希望作者让我加一下群呗1070993055

**Comment by CodFrm** [comment]
@BG8CFB 预计下个版本加入随机值,题库还是需要采集,答题前先用同学账号采集一次最佳

火狐这个我还得再看看...可以先试一下打包浏览器版本或者用chrome系列的浏览器安装crx插件

**Comment by wankaiss** [comment]
@BG8CFB 按照你的描述，岂不是我直接观看下一集就直接判定为作弊了？:broken_heart: 我只是直接用的脚本在console中
