### ISSUE TITLE
试题已经自动填充完了，但是要等好几分钟才跳转

### ISSUE THREAD

**Issue by wentaoer525** [CodFrm/cxmooc-tools#82]
比如第一节课试题自动填充完了，显示1分钟后跳转，第二节课显示2分钟后跳转，以此类推，有的时候还显示13分钟后跳转。

**Comment by CodFrm** [comment]
这个是时间间隔，防止过快被检测，下个版本会进行优化

**Comment by suizishuo** [comment]
你好，我一直在用这个软件最近不知道为什么，看完课程以后，不显示完成，超星雅尔。你有qq或者微信方式吗？需要帮忙我的vx：suizishuo

**Comment by CodFrm** [comment]
> 你好，我一直在用这个软件最近不知道为什么，看完课程以后，不显示完成，超星雅尔。你有qq或者微信方式吗？需要帮忙我的vx：suizishuo

@suizishuo 有qq群,你也可以在github放上截图,具体一点的描述问题

**Comment by suizishuo** [comment]
QQ群多少


在2019年10月09日 09:18，CodFrm 写道：

你好，我一直在用这个软件最近不知道为什么，看完课程以后，不显示完成，超星雅尔。你有qq或者微信方式吗？需要帮忙我的vx：suizishuo

@suizishuo 有qq群,你也可以在github放上截图,具体一点的描述问题

**Comment by CodFrm** [comment]
@suizishuo 首页有写。。。614202391
