### ISSUE TITLE
自动跳过视频不是正常工作的

### ISSUE THREAD

**Issue by gilbertchenzhe** [CodFrm/cxmooc-tools#84]
**错误描述**
点击网课右侧的标题节点后，不管有没有看完（完成）的视频，都会跳过，跳到最底部的视频，然后提示文字“所有节点已完成”

**错误提示和日志内容**
页面文字提示：
NaN分钟后视频将自动跳转到下一个节点
![image](https://user-images.githubusercontent.com/13924860/59992468-80a73c00-967e-11e9-81f8-f9316887aa73.png)

**出现时间**
2019.6.24 能复现

**错误版本**
Chrome 版本 73.0.3683.86
超星慕课小工具version 2.104

**Comment by gilbertchenzhe** [comment]
![image](https://user-images.githubusercontent.com/13924860/59994289-dfbc7f00-9685-11e9-9e52-80575a11fb65.png)

**Comment by CodFrm** [comment]
升级到最新的版本试一下

**Comment by gilbertchenzhe** [comment]
> 升级到最新的版本试一下,使用插件版本

根据楼上作者的反馈，我直接使用Chrome浏览器的插件版本，该版本没有我反馈的BUG问题。
如果有我反馈的问题的，请在版本发布页面，安装最新的插件版本。
[https://github.com/CodFrm/cxmooc-tools/releases](url)
