### ISSUE TITLE
能否添加默认选择公网或者校内网的编辑选项

### ISSUE THREAD

**Issue by tydaytygx** [CodFrm/cxmooc-tools#89]
能否添加默认选择公网或者校内网的编辑选项
在某些环境中需要切换默认的网络

**Comment by CodFrm** [comment]
可以考虑,现在的话应该是会记录你最后一次的选择(不过好像会经常失效)

**Comment by tydaytygx** [comment]
当每个大章节跳转的时候容易失效，章节中的小节不会失效

**Comment by CodFrm** [comment]
https://github.com/CodFrm/cxmooc-tools/commit/41b244d48e5f9fdd6f456683ad603115a7a6e333
