### ISSUE TITLE
屏蔽观看视频时出现的小测验

### ISSUE THREAD

**Issue by logique233** [CodFrm/cxmooc-tools#9]
如果你觉得验证码或小测验很讨厌，请尝试向兼容 AdBlock Plus 语法的广告过滤扩展添加这条自定义规则：

`*.chaoxing.com/richvideo/initdatawithviewer*`

应用此规则后播放器可能提示“加载资源地址出错！”，这是正常现象并表明规则已正常生效。
**来源：**[https://greasyfork.org/zh-CN/scripts/20059-chaoxing](https://greasyfork.org/zh-CN/scripts/20059-chaoxing)

**Comment by CodFrm** [comment]
可以这样去掉吗0.0,一直用AdBlock Plus,还没尝试过这样玩

**Comment by kuangshao11** [comment]
fuck chaoxing，hahahha
