### ISSUE TITLE
看完一个视频的话无法自动跳转到下一个视频

### ISSUE THREAD

**Issue by longlifedahan** [CodFrm/cxmooc-tools#90]
**错误描述**
看完一个视频的话无法自动跳转到下一个视频，必须保持这个界面才可以自动跳转到下一个视频吗？我大概敲了一个小时代码，然后发现居然只过了一章，必须打开挂机窗口才可以自动播放下一个视频吗？

你所遇到的错误是怎么样的?最好提供错误截图

**错误提示和日志内容**
有没有错误的提示,和日志的内容(在浏览器中f12打开开发者工具，console的错误提示,日志内容在Filter中填入cxmooc,然后全部复制上来)

**出现时间**
你是怎么操作出现的这个错误?能不能复现呢?(再次出现)

**错误版本**
你的浏览器版本和扩展的版本,油猴,Chrome,还是火狐?

**Comment by CodFrm** [comment]
不要最小化

**Comment by longlifedahan** [comment]
在 2019-09-10 11:36:22，CodFrm <notifications@github.com> 写道：

>不要最小化
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly, view it on GitHub, or mute the thread.
感谢，明白了
