### ISSUE TITLE
Chrome浏览器无法安装使用

### ISSUE THREAD

**Issue by zhz1237ok** [CodFrm/cxmooc-tools#92]
![image](https://user-images.githubusercontent.com/38283893/65423077-c240b200-de3a-11e9-961c-6240cc02efbc.png)
![image](https://user-images.githubusercontent.com/38283893/65423087-ca98ed00-de3a-11e9-942b-b1b41651021d.png)
![image](https://user-images.githubusercontent.com/38283893/65423099-d1bffb00-de3a-11e9-897c-23aa5a7de45f.png)

**Comment by zhz1237ok** [comment]
具体体现是鼠标移开就不会继续播放视频了

**Comment by CodFrm** [comment]
这个错误是正常的，提供一下观看截图

**Comment by zhz1237ok** [comment]
我没在用，是给同学用的，现在换成了集成浏览器的那个然后拖了新版crx进去，似乎是可以了
