### ISSUE TITLE
智慧树 无法自动跳到下一个视频

### ISSUE THREAD

**Issue by blackyau** [CodFrm/cxmooc-tools#96]
**错误描述**
视频正常播放完毕，进度已达100%，但是没有自动跳到下一个视频。会重新播放当前视频。

**错误提示和日志内容**
![Console 截图1](https://i.loli.net/2019/11/28/RaPDp8JxltnKi74.jpg)
![Console 截图2](https://i.loli.net/2019/11/28/agUwP9yWIv5YxKN.png)

**出现时间**
点击播放视频，鼠标焦点没有离开过浏览器，一直都在这播放视频这个界面。能复现

**错误版本**
Chrome 78.0.3904.108（正式版本） （64 位）
浏览器扩展版本 2.1.1

**Comment by CodFrm** [comment]
间隔时间默认是5(+-2.5)分钟,请检查一下是否是间隔时间的问题

**Comment by blackyau** [comment]
@CodFrm 回复神速...我在测试看看

**Comment by blackyau** [comment]
@CodFrm 经测试，确实播放时间足够长，就会在播放时中途跳到下一视频去。
这个课程的视频的时间太短了...如果没问题请 Close issues
![视频时长](https://i.loli.net/2019/11/28/IdMo48iSCtOYF1E.png)

**Comment by CodFrm** [comment]
@blackyau 可以自行调整间隔时间,可以拥有小数点  0.5(半分钟)
